%
% demoEngine.compute.mRGCmosaicActivation
%
function mRGCmosaicActivation(theDataFileName, mRGCtemporalFiltersSources, exportVisualizationRootDirectory, exportVisualizationPDFdirectory, ...
            exportVisualizationVideoDirectory, exportDataDirectory, theTargetmRGCindex)
    
    % Load the mRGC temporal filters
    theSourceFile = fullfile(...
        mRGCtemporalFiltersSources.rootDir, mRGCtemporalFiltersSources.derivedInnerRetinaImpulseResponseCenterDataFile);
    d = load(theSourceFile, 'theDerivedInnerRetinaFiniteTimeImpulseResponseData');
    innerRetinaCenterImpulseResponseData = d.theDerivedInnerRetinaFiniteTimeImpulseResponseData;
    

    theSourceFile = fullfile(...
        mRGCtemporalFiltersSources.rootDir, mRGCtemporalFiltersSources.derivedInnerRetinaImpulseResponseSurroundDataFile);
    d = load(theSourceFile, 'theDerivedInnerRetinaFiniteTimeImpulseResponseData');
    innerRetinaSurroundImpulseResponseData = d.theDerivedInnerRetinaFiniteTimeImpulseResponseData;



    assert(all(abs(innerRetinaCenterImpulseResponseData.temporalSupportSeconds(:)-innerRetinaSurroundImpulseResponseData.temporalSupportSeconds(:)))<10*eps, ...
        'temporal supports of center and surround do not match');

    % Normalize to unit peak amplitude
    innerRetinaCenterImpulseResponseData.amplitude = innerRetinaCenterImpulseResponseData.amplitude / max(abs(innerRetinaCenterImpulseResponseData.amplitude(:)));
    innerRetinaSurroundImpulseResponseData.amplitude = innerRetinaSurroundImpulseResponseData.amplitude / max(abs(innerRetinaSurroundImpulseResponseData.amplitude(:)));
    

    innerRetinaTemporalFilters = struct(...
        'temporalSupportSeconds', innerRetinaCenterImpulseResponseData.temporalSupportSeconds, ...
        'centerImpulseResponseFunction', innerRetinaCenterImpulseResponseData.amplitude, ...
        'surroundImpulseResponseFunction', innerRetinaSurroundImpulseResponseData.amplitude);
        
    clear('innerRetinaSurroundImpulseResponseData', 'innerRetinaCenterImpulseResponseData');


   
    temporalFrequencySupportHz = 0:0.5:200;
    params = RGCmodels.BenardeteKaplan1997.figure6CenterSurroundFilterParams('ON');

    theTargetCascadedFilterTTF = RGCmodels.BenardeteKaplan1997.oneStageHighPassNstageLowPassFilterCascadeTTF(...
                params.centerIR.pVector, temporalFrequencySupportHz);
    theCenterImpulseResponseData = RGCMosaicConstructor.temporalFilterEngine.sampledTTFtoTemporalImpulseFunction(...
                    theTargetCascadedFilterTTF, temporalFrequencySupportHz, ...
                    'causal', false, ...
                    'upsample', 1);



    theTargetCascadedFilterTTF = RGCmodels.BenardeteKaplan1997.oneStageHighPassNstageLowPassFilterCascadeTTF(...
                params.surroundIR.pVector, temporalFrequencySupportHz);
    theSurroundImpulseResponseData = RGCMosaicConstructor.temporalFilterEngine.sampledTTFtoTemporalImpulseFunction(...
                    theTargetCascadedFilterTTF, temporalFrequencySupportHz, ...
                    'causal', false, ...
                    'upsample', 1);


    centerAmplitude = interp1(theCenterImpulseResponseData.temporalSupportSeconds, theCenterImpulseResponseData.amplitude, innerRetinaTemporalFilters.temporalSupportSeconds);
    surroundAmplitude = interp1(theSurroundImpulseResponseData.temporalSupportSeconds, theSurroundImpulseResponseData.amplitude, innerRetinaTemporalFilters.temporalSupportSeconds);

    BenardeteKaplanFig6ONfilters = struct(...
        'temporalSupportSeconds', innerRetinaTemporalFilters.temporalSupportSeconds, ...
        'centerImpulseResponseFunction', centerAmplitude, ...
        'surroundImpulseResponseFunction', surroundAmplitude);


    figure(5555);
    ax = subplot(1,2,1);
    plot(ax, innerRetinaTemporalFilters.temporalSupportSeconds, innerRetinaTemporalFilters.centerImpulseResponseFunction, 'r-', 'LineWidth', 1.5);
    hold(ax, 'on');
    plot(innerRetinaTemporalFilters.temporalSupportSeconds, innerRetinaTemporalFilters.surroundImpulseResponseFunction, 'b-', 'LineWidth', 1.5);
    

    ax = subplot(1,2,2);
    plot(ax, BenardeteKaplanFig6ONfilters.temporalSupportSeconds, BenardeteKaplanFig6ONfilters.centerImpulseResponseFunction, 'r-', 'LineWidth', 1.5);
    hold on;
    plot(ax,BenardeteKaplanFig6ONfilters.temporalSupportSeconds, BenardeteKaplanFig6ONfilters.surroundImpulseResponseFunction, 'b-', 'LineWidth', 1.5);
    
    pause


    % Load the data
    theDataFileName = fullfile(exportVisualizationRootDirectory, exportDataDirectory, theDataFileName);
    load(theDataFileName, ...
        'theMRGCmosaic', ...
        'theConeMosaicSpatioTemporalExcitationResponse', ...
        'theConeExcitationsResponseTemporalSupportSeconds', ...
        'theConeMosaicSpatioTemporalPhotocurrentResponses', ...
        'thePhotocurrentResponseTemporalSupportSeconds');



    % compute cone modulations from excitations
    meanConeExcitations = mean(theConeMosaicSpatioTemporalExcitationResponse, 3);
    theConeMosaicSpatioTemporalModulationsResponse = bsxfun(@times, bsxfun(@minus, theConeMosaicSpatioTemporalExcitationResponse, meanConeExcitations), 1./meanConeExcitations);


    % Compute the mRGC mosaic response (cone excitations + no filtering)
    [theMRGCmosaicResponse, ~, theMRGCMosaicResponseTemporalSupportSeconds] = ...
        theMRGCmosaic.compute(...
            theConeMosaicSpatioTemporalModulationsResponse, ...
            theConeExcitationsResponseTemporalSupportSeconds);

    theMRGCmosaicResponseDictionary = containers.Map();
    theMRGCmosaicResponseDictionary('cone modulations alone') = struct(...
        'theMRGCmosaicResponse', theMRGCmosaicResponse, ...
        'theTemporalSupportSeconds', theMRGCMosaicResponseTemporalSupportSeconds);
        

    % Compute the mRGC mosaic response (cone excitations + no filtering) - OFF cell
    theMRGCmosaicResponse = theMRGCmosaic.compute(...
            theConeMosaicSpatioTemporalModulationsResponse, ...
            theConeExcitationsResponseTemporalSupportSeconds, ...
            'flipLinearResponsePolarityForCellsWithIndices', theTargetmRGCindex);

    theMRGCmosaicResponseDictionary(sprintf('cone modulations alone (mRGC #%d with flipped polarity)', theTargetmRGCindex)) = struct(...
        'theMRGCmosaicResponse', theMRGCmosaicResponse, ...
        'theTemporalSupportSeconds', theMRGCMosaicResponseTemporalSupportSeconds);

            

    % Cone excitations + BK filter
    [theMRGCmosaicResponse, ~, theMRGCMosaicResponseTemporalSupportSeconds] = ...
        theMRGCmosaic.compute(...
            theConeMosaicSpatioTemporalModulationsResponse, ...
            theConeExcitationsResponseTemporalSupportSeconds, ...
            'withCenterSurroundTemporalFilters', BenardeteKaplanFig6ONfilters);

    theMRGCmosaicResponseDictionary('cone modulations + BK filters') = struct(...
        'theMRGCmosaicResponse', theMRGCmosaicResponse, ...
        'theTemporalSupportSeconds', theMRGCMosaicResponseTemporalSupportSeconds);




    % Cone modulation + BK filter (OFF cell)
    theMRGCmosaicResponse = theMRGCmosaic.compute(...
            theConeMosaicSpatioTemporalModulationsResponse, ...
            theConeExcitationsResponseTemporalSupportSeconds, ...
            'withCenterSurroundTemporalFilters', BenardeteKaplanFig6ONfilters, ...
            'flipLinearResponsePolarityForCellsWithIndices', theTargetmRGCindex);

    theMRGCmosaicResponseDictionary(sprintf('cone modulations + BK filters (mRGC #%d with flipped polarity)', theTargetmRGCindex)) = struct(...
        'theMRGCmosaicResponse', theMRGCmosaicResponse, ...
        'theTemporalSupportSeconds', theMRGCMosaicResponseTemporalSupportSeconds);



    % Compute the mRGC mosaic response (photocurrents - only)
    [theMRGCmosaicResponse, ~, theMRGCMosaicResponseTemporalSupportSeconds] = ...
        theMRGCmosaic.compute(...
            theConeMosaicSpatioTemporalPhotocurrentResponses, ...
            thePhotocurrentResponseTemporalSupportSeconds);

    theMRGCmosaicResponseDictionary('photocurrents only') = struct(...
        'theMRGCmosaicResponse', theMRGCmosaicResponse, ...
        'theTemporalSupportSeconds', theMRGCMosaicResponseTemporalSupportSeconds);


    % Compute the mRGC mosaic response (photocurrents - only) - OFF cell
    theMRGCmosaicResponse = theMRGCmosaic.compute(...
            theConeMosaicSpatioTemporalPhotocurrentResponses, ...
            thePhotocurrentResponseTemporalSupportSeconds);

    theMRGCmosaicResponseDictionary(sprintf('photocurrents only (mRGC #%d with flipped polarity)', theTargetmRGCindex)) = struct(...
        'theMRGCmosaicResponse', theMRGCmosaicResponse, ...
        'theTemporalSupportSeconds', theMRGCMosaicResponseTemporalSupportSeconds);


    % Compute the mRGC mosaic response (photocurrents + inner retina filter)
    [theMRGCmosaicResponse, ~, theMRGCMosaicResponseTemporalSupportSeconds] = ...
        theMRGCmosaic.compute(...
            theConeMosaicSpatioTemporalPhotocurrentResponses, ...
            thePhotocurrentResponseTemporalSupportSeconds, ...
            'withCenterSurroundTemporalFilters', innerRetinaTemporalFilters);

    theMRGCmosaicResponseDictionary('photocurrents + inner retina filter cascade') = struct(...
        'theMRGCmosaicResponse', theMRGCmosaicResponse, ...
        'theTemporalSupportSeconds', theMRGCMosaicResponseTemporalSupportSeconds);


    % Compute the mRGC mosaic response (photocurrents + inner retina filter) - OFF cell
    theMRGCmosaicResponse = theMRGCmosaic.compute(...
            theConeMosaicSpatioTemporalPhotocurrentResponses, ...
            thePhotocurrentResponseTemporalSupportSeconds, ...
            'withCenterSurroundTemporalFilters', innerRetinaTemporalFilters, ...
            'flipLinearResponsePolarityForCellsWithIndices', theTargetmRGCindex);

    theMRGCmosaicResponseDictionary(sprintf('photocurrents + inner retina filter cascade (mRGC #%d with flipped polarity)', theTargetmRGCindex)) = struct(...
        'theMRGCmosaicResponse', theMRGCmosaicResponse, ...
        'theTemporalSupportSeconds', theMRGCMosaicResponseTemporalSupportSeconds);




    % Compute the mRGC mosaic response (photocurrents + inner retina filter, surround-only)
    theMRGCmosaicResponse = theMRGCmosaic.compute(...
            theConeMosaicSpatioTemporalPhotocurrentResponses, ...
            thePhotocurrentResponseTemporalSupportSeconds, ...
            'withCenterSurroundTemporalFilters', innerRetinaTemporalFilters, ...
            'deactivatedCenter', true);

    theMRGCmosaicResponseDictionary('photocurrents + inner retina filter cascade - surround only') = struct(...
        'theMRGCmosaicResponse', theMRGCmosaicResponse, ...
        'theTemporalSupportSeconds', theMRGCMosaicResponseTemporalSupportSeconds);



    % Compute the mRGC mosaic response (photocurrents + inner retina filter, center-only)
    theMRGCmosaicResponse = theMRGCmosaic.compute(...
            theConeMosaicSpatioTemporalPhotocurrentResponses, ...
            thePhotocurrentResponseTemporalSupportSeconds, ...
            'withCenterSurroundTemporalFilters', innerRetinaTemporalFilters, ...
            'deactivatedSurround', true);

    theMRGCmosaicResponseDictionary('photocurrents + inner retina filter cascade - center only') = struct(...
        'theMRGCmosaicResponse', theMRGCmosaicResponse, ...
        'theTemporalSupportSeconds', theMRGCMosaicResponseTemporalSupportSeconds);



    % Compute the mRGC mosaic response (cone modulations + inner retina
    % filter) - CONTROL
    [theMRGCmosaicResponse, ~, theMRGCMosaicResponseTemporalSupportSeconds] = ...
        theMRGCmosaic.compute(...
            theConeMosaicSpatioTemporalModulationsResponse, ...
            theConeExcitationsResponseTemporalSupportSeconds, ...
            'withCenterSurroundTemporalFilters', innerRetinaTemporalFilters);

    theMRGCmosaicResponseDictionary('modulations + inner retina filter cascade') = struct(...
        'theMRGCmosaicResponse', theMRGCmosaicResponse, ...
        'theTemporalSupportSeconds', theMRGCMosaicResponseTemporalSupportSeconds);


    fprintf('Appending mRGCMosaic responses dictionary to %s\n', theDataFileName);

    % Append theMRGCmosaicResponseDictionary
    save(theDataFileName, ...
        'theMRGCmosaicResponseDictionary', ...
        '-append');


end
