function plotConeMosaics()

    % Generate a treeshrew cone mosaic
    treeShrewMosaicSizeDegs = [1.9 1.9];
    theTreeShrewConeMosaic = cMosaicTreeShrewCreate(...
        'sizeDegs', treeShrewMosaicSizeDegs);
    plotConeMosaic(theTreeShrewConeMosaic, sprintf('tree shrew mosaic (%2.1f x %2.1f degs)', treeShrewMosaicSizeDegs(1), treeShrewMosaicSizeDegs(2)), 'treeShrewConeMosaic.pdf');

    % Generate human cone mosaic
    humanConeMosaicSizeDegs = [0.5 0.5];
    theHumanConeMosaic = cMosaic(...
        'whichEye', 'right eye', ...         
        'sizeDegs', humanConeMosaicSizeDegs);

    plotConeMosaic(theHumanConeMosaic, sprintf('human cone mosaic (%2.1f x %2.1f degs)', humanConeMosaicSizeDegs(1), humanConeMosaicSizeDegs(2)), 'humanConeMosaic.pdf');

end


function plotConeMosaic(theConeMosaic, plotTitle, pdfFileName)

    ff = PublicationReadyPlotLib.figureComponents('1x1 giant square mosaic');
	hFig = figure(1); clf;
    theAxes = PublicationReadyPlotLib.generatePanelAxes(hFig,ff);
    ax = theAxes{1,1};

    domainUnits = 'microns';
    domainVisualizationTicks = struct(...
            'x',  sign(theConeMosaic.eccentricityMicrons(1)) * round(abs(theConeMosaic.eccentricityMicrons(1))) + 30*(-2:2), ...
            'y',  sign(theConeMosaic.eccentricityMicrons(2)) * round(abs(theConeMosaic.eccentricityMicrons(2))) + 30*(-2:2));


    activation = zeros(1,1,theConeMosaic.conesNum);
    activation(1,1,theConeMosaic.lConeIndices) = activation(1,1,theConeMosaic.lConeIndices) + 0.7;
    activation(1,1,theConeMosaic.mConeIndices) = activation(1,1,theConeMosaic.mConeIndices) + 0.5;
    activation(1,1,theConeMosaic.sConeIndices) = activation(1,1,theConeMosaic.sConeIndices) + 0.2;
    theConeMosaic.visualize('figureHandle', hFig, ...
            'axesHandle', ax, ...
            'domain', domainUnits, ...
            'domainVisualizationTicks', domainVisualizationTicks, ...
            'visualizedConeAperture', 'lightcollectingarea4sigma', ... %'activation', activation, %'activationRange', [0 1], ...
            'activationcolormap', brewermap(256, '*greys'), ...
            'visualizedConeApertureThetaSamples', 32, ...
            'conesAlpha', 0.8, ...
            'conesEdgeAlpha', 0.9, ...
            'backgroundColor', [1 1 1], ...
            'clearAxesBeforeDrawing', false, ...
            'plotTitleColor', [0.5 0.5 0.5], ...
            'fontSize', 16, ...
            'verbose', false, ...
            'plotTitle', plotTitle, ...
            'plotTitleFontSize', 16 ...
            );

    PublicationReadyPlotLib.applyFormat(ax,ff);
    % PublicationReadyPlotLib.offsetAxes(ax, ff, xLims, yLims); 

    theFiguresDir = fullfile(ISETBioPaperAndGrantCodeRootDirectory, 'local', mfilename);
    if (~exist(theFiguresDir,'dir'))
        mkdir(theFiguresDir);
    end

    thePDFfileName = fullfile(theFiguresDir, pdfFileName);
    NicePlot.exportFigToPDF(thePDFfileName,hFig,  300);

end