function t_temporalDynamicsFixationalEMphotocurrentDemo(options)
% Demo the interactions b/n fixationalEM, phototransduction, and mRGC temporal dynamics
%
% Description:
%   Demo the interactions b/n fixationalEM, phototransduction, and mRGC temporal dynamics
%
% History:
%    05/04/26  NPC  Wrote it.
%
% Examples:
%{
    t_temporalDynamicsFixationalEMphotocurrentDemo(...
        'rgcMosaicName', 'JCNpaperTemporal7DegsMosaic', ...
        'opticsSubjectName', 'JCNpaperDefaultSubject', ...
        'visualizeMRGCmosaic',true);

%}

arguments


% ---- Mosaic specifiers for selecting a prebaked mRGC mosaic ------

    % See RGCMosaicConstructor.helper.utils.initializeRGCMosaicGenerationParameters
    % for what is available and to add new mosaics
    options.rgcMosaicName (1,:) char = 'JCNpaperNasal2DegsTinyMosaic';


    % ---- Which species to employ ----
    % Choose between {'macaque', 'human'}. If 'macaque' is chosen, the input
    % cone mosaic has a 1:1 L/M cone ratio.
    options.coneMosaicSpecies  (1,:) char {mustBeMember(options.coneMosaicSpecies,{'human','macaque'})} = 'human';


    % ----- Which subject optics to employ -----
    options.opticsSubjectName (1,:) ...
        char ...
        {...
        mustBeMember(options.opticsSubjectName, ...
            { ...
            'JCNpaperDefaultSubject' ...
            'JCNpaperSecondSubject' ...
            'VSS2024TalkFirstSubject' ...
            'VSS2024TalkSecondSubject' ...
            'JCNpaperStrehlRatio_0.87' ...
            'JCNpaperStrehlRatio_0.72' ...
            'JCNpaperStrehlRatio_0.59' ...
            'JCNpaperStrehlRatio_0.60' ...
            'JCNpaperStrehlRatio_0.27' ...
            'JCNpaperStrehlRatio_0.23' ...
            'JCNpaperStrehlRatio_0.21' ...
            'JCNpaperStrehlRatio_0.19' ...
            'JCNpaperStrehlRatio_0.09' ...
            } ...
            ) ...
        } ...
        = 'JCNpaperDefaultSubject';


    % ------ targetVisualSTF options ----
    % Options are : {'default', 'x1.3 RsRcRatio'}
    % These are with respect to the macaque data of the Croner & Kaplan '95 study
    % 'default': target the mean Rs/Rc, and the mean Ks/Kc (Rs/Rc)^2
    % See RGCMosaicConstructor.helper.surroundPoolingOptimizerEngine.generateTargetVisualSTFmodifiersStruct
    % for all existing options
    options.targetVisualSTFdescriptor (1,:) char = 'default';

    % Submosaic to map
    options.cropParams = [];

    % Different options for the optics
    options.opticsForTTFresponses = [];

    % Wavefront spatial samples
    options.opticsWavefrontSpatialSamples = [];

    % Display params
    options.meanLuminanceCdM2 (1,1) double = 60;
    options.displayType (1,:) char = '';
    options.displayLuminanceHeadroomPercentage (1,1) double = 5/100;
    options.adjustBackgroundChromaticityToEqualizeLandMconeExcitations (1,1) logical = false;
    options.coneFundamentalsOptimizedForStimPosition (1,1) logical = false;


    % Spatial position params
    options.stimulusPixelSizeAsFractionOfConeAperture (1,1) double = 0.5;
    options.stimulusMaxSupportDegs (1,:) double = [];
    options.stimulusPositionDegs (1,:) double = [];
    options.stimulusSizeDegs (1,:) double = [];

    % Photocurrent (full biophysical model) params
    options.photocurrentParams (1,1) = struct(...
        'osBiophysicalModelWarmUpTimeSeconds',  1.0, ...
        'osBiophysicalModelTemporalResolutionSeconds',  1e-5, ...
        'temporalResolutionSeconds',  0.5/1000);

    % Nonlinearities
    options.mRGCNonLinearityParamsStruct = [];
    options.mRGCsOperateOnBackgroundAdaptedPhotocurrents (1,1) logical = true;


    % Visualizations
    options.visualizeMRGCmosaic (1,1) logical = false;

    % ---- Choices of actions to perform ----
    % Whether to compute the input cone mosaic TTF responses
    options.computeInputConeMosaicResponses (1,1) logical = false;
    options.computeInputConeMosaicResponsesBasedOnConeExcitations (1,1) logical = true;
    options.computeInputConeMosaicResponsesBasedOnPhotocurrents (1,1) logical = true;
    options.computePhotocurrentResponsesOnlyForInputsToSingleRGCwithIndex (1,:) double = [];

    options.computeMRGCMosaicResponses (1,1) logical = false;


    % Whether to close previously open figures
    options.closePreviouslyOpenFigures (1,1) logical = true;

    options.exportVisualizationPDF (1,1) logical = false;
    options.exportVisualizationPNG (1,1) logical = false;
end

    % Set flags from key/value pairs
    
    % Mosaic specifiers for selecting a prebaked mRGC mosaic
    rgcMosaicName = options.rgcMosaicName;
    coneMosaicSpecies = options.coneMosaicSpecies;
    opticsSubjectName = options.opticsSubjectName;
    targetVisualSTFdescriptor = options.targetVisualSTFdescriptor;
    
    % Mosaic cropping
    cropParams = options.cropParams;
    
    % Optics to employ for the computations
    opticsForTTFresponses = options.opticsForTTFresponses;
    opticsWavefrontSpatialSamples = options.opticsWavefrontSpatialSamples;
    
    % Display params
    meanLuminanceCdM2 = options.meanLuminanceCdM2;
    displayType = options.displayType;
    displayLuminanceHeadroomPercentage = options.displayLuminanceHeadroomPercentage;
    coneFundamentalsOptimizedForStimPosition = options.coneFundamentalsOptimizedForStimPosition;
    adjustBackgroundChromaticityToEqualizeLandMconeExcitations = options.adjustBackgroundChromaticityToEqualizeLandMconeExcitations;
    
    % Spatial params
    stimulusPixelSizeAsFractionOfConeAperture = options.stimulusPixelSizeAsFractionOfConeAperture;
    stimulusMaxSupportDegs = options.stimulusMaxSupportDegs;
    stimulusPositionDegs = options.stimulusPositionDegs;
    stimulusSizeDegs =  options.stimulusSizeDegs;


    % Photocurrent params
    photocurrentParams = options.photocurrentParams;
    
    mRGCsOperateOnBackgroundAdaptedPhotocurrents = options.mRGCsOperateOnBackgroundAdaptedPhotocurrents;
    
    % Nonlinearities
    mRGCNonLinearityParamsStruct = options.mRGCNonLinearityParamsStruct;
    
    % Visualizations
    visualizeMRGCmosaic = options.visualizeMRGCmosaic;
    exportVisualizationPDF = options.exportVisualizationPDF;
    exportVisualizationPNG = options.exportVisualizationPNG;
    
    % Close previously open figures
    closePreviouslyOpenFigures = options.closePreviouslyOpenFigures;
    
    if (closePreviouslyOpenFigures)
        % Close any stray figs
        close all;
    end

    % Load the mRGCmosaic specified by the passed parameters:
    %   coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor
    % and generate the optics that were used to synthesize the mosaic
    [theMRGCmosaic, theOptics, thePSFatTheMosaicEccentricity, ...
      prebakedMRGCMosaicDir, prebakedMRGCMosaicFilename] = mRGCMosaic.loadPrebakedMosaic(...
            coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor, ...
            'computeTheMosaicOptics', true, ...
            'opticsToEmploy', opticsForTTFresponses, ...
            'wavefrontSpatialSamples', opticsWavefrontSpatialSamples, ...
            'cropParams', cropParams);
    
    % Plot a smaller region of the mRGC mosaic with the PSF superimposed
    visualizedWidthDegs = 0.5;
    narrowDomainVisualizationLimits(1:2) = theMRGCmosaic.eccentricityDegs(1) + [-0.5 0.5]*visualizedWidthDegs;
    narrowDomainVisualizationLimits(3:4) = theMRGCmosaic.eccentricityDegs(2) + [-0.5 0.5]*visualizedWidthDegs;
    narrowDomainVisualizationTicks = struct(...
        'x', -30:0.2:0, ...
        'y', -10:0.2:10);
    
    % Generate figure dir if it does not exist
    exportVisualizationPDFrootDirectory = ISETBioPaperAndGrantCodeFigureDirForScript(mfilename);
    exportVisualizationPDFdirectory = 'staticPDFs';
    
    if (visualizeMRGCmosaic)
        fancyMosaicVisualization(theMRGCmosaic, ...
            narrowDomainVisualizationLimits, ...
            narrowDomainVisualizationTicks, ...
            exportVisualizationPDFrootDirectory, ...
            exportVisualizationPDFdirectory);
    end


    % Load an HDR scene

end


function fancyMosaicVisualization(theMRGCmosaic, ...
    domainVisualizationLimits, ...
    domainVisualizationTicks, ...
    exportVisualizationPDFrootDirectory, ...
    exportVisualizationPDFdirectory)


    % Generate a PSF visualization data struct (containing the vLambda-weighted PSF) for
    % visualization purposes
    PSFvisualizationOffset = theMRGCmosaic.eccentricityDegs - [mean(narrowDomainVisualizationLimits(1:2)) mean(narrowDomainVisualizationLimits(3:4))];
    vLambdaWeightedPSF.data = RGCMosaicAnalyzer.compute.vLambdaWeightedPSF(thePSFatTheMosaicEccentricity);
    vLambdaWeightedPSF.supportXdegs = thePSFatTheMosaicEccentricity.supportX/60 - PSFvisualizationOffset(1);
    vLambdaWeightedPSF.supportYdegs = thePSFatTheMosaicEccentricity.supportY/60 - PSFvisualizationOffset(2);


    % Visualize the full mosaic of RF centers using a representation
    % like the representation used in visualizing
    % mosaics of RGCs in typical in-vitro experiments (e.g. by the Chichilnisky lab)
    minCenterConeWeight = mRGCMosaic.sensitivityAtPointOfOverlap;
    

    % Get ready for publication-quality visualization
    ff = PublicationReadyPlotLib.figureComponents('1x1 giant rectangular-double wide mosaic', ...
        'darkScheme', true);
    
    % Plot the mosaic of mRGC RF centers only
    hFig = figure(1); clf;
    theAxes = PublicationReadyPlotLib.generatePanelAxes(hFig,ff);
    ax = theAxes{1,1};
    
    tmp = ff.backgroundColor;
    ff.backgroundColor = ff.legendBackgroundColor;
    ff.legendBackgroundColor = tmp;
    
    theMRGCmosaic.visualize(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'identifyInputCones', false, ...
        'identifyPooledCones', false, ...
        'minConeWeightVisualized', minCenterConeWeight, ...
        'centerSubregionContourSamples', 32, ...
        'plottedRFoutlineFaceAlpha', 1.0, ...
        'plottedRFoutlineLineWidth', 1.0, ...
        'plottedRFoutlineFaceColor', [1 1 1], ...
        'plottedRFoutlineEdgeColor',  [0 0 0], ...
        'domainVisualizationLimits', domainVisualizationLimits, ...
        'domainVisualizationTicks', domainVisualizationTicks, ...
        'plotTitle', sprintf('min center weight visualized: %2.3f', minCenterConeWeight), ...
        'withFigureFormat', ff, ...
        'backgroundColor', ff.legendBackgroundColor, ...
        'clearAxesBeforeDrawing', false, ...
        'visualizationPDFfileName', sprintf('fullMRGCmosaicMinCenterConeWeight_%2.3f', minCenterConeWeight), ...
        'exportVisualizationPDF', true, ...
        'exportVisualizationPNG', true, ...
        'exportVisualizationPDFrootDirectory', exportVisualizationPDFrootDirectory, ...
        'exportVisualizationPDFdirectory', exportVisualizationPDFdirectory);
    hold(ax, 'on');

    % double rendering
    theMRGCmosaic.visualize(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'identifyInputCones', false, ...
        'identifyPooledCones', false, ...
        'minConeWeightVisualized', minCenterConeWeight, ...
        'centerSubregionContourSamples', 32, ...
        'plottedRFoutlineFaceAlpha', 0.5, ...
        'plottedRFoutlineLineWidth', 4.0, ...
        'plottedRFoutlineEdgeColor', [0 0 0], ...
        'plottedRFoutlineFaceColor',  [0. 1.0 0.0], ...
        'domainVisualizationLimits', domainVisualizationLimits, ...
        'domainVisualizationTicks', domainVisualizationTicks, ...
        'plotTitle', sprintf('min center weight visualized: %2.3f', minCenterConeWeight), ...
        'withFigureFormat', ff, ...
        'backgroundColor', ff.legendBackgroundColor, ...
        'clearAxesBeforeDrawing', false, ...
        'visualizationPDFfileName', sprintf('fullMRGCmosaicMinCenterConeWeight_%2.3f', minCenterConeWeight), ...
        'exportVisualizationPDF', true, ...
        'exportVisualizationPNG', true, ...
        'exportVisualizationPDFrootDirectory', exportVisualizationPDFrootDirectory, ...
        'exportVisualizationPDFdirectory', exportVisualizationPDFdirectory);
    
    theMRGCmosaic.visualize(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'identifyInputCones', false, ...
        'identifyPooledCones', false, ...
        'minConeWeightVisualized', minCenterConeWeight, ...
        'centerSubregionContourSamples', 32, ...
        'plottedRFoutlineFaceAlpha', 0.0, ...
        'plottedRFoutlineLineWidth', 2, ...
        'plottedRFoutlineEdgeColor', [0 1 0 ], ...
        'plottedRFoutlineFaceColor',  [0. 1 0.0], ...
        'domainVisualizationLimits', domainVisualizationLimits, ...
        'domainVisualizationTicks', domainVisualizationTicks, ...
        'plotTitle', sprintf('min center weight visualized: %2.3f', minCenterConeWeight), ...
        'withFigureFormat', ff, ...
        'backgroundColor', ff.legendBackgroundColor, ...
        'clearAxesBeforeDrawing', false, ...
        'visualizationPDFfileName', sprintf('fullMRGCmosaicMinCenterConeWeight_%2.3f', minCenterConeWeight), ...
        'exportVisualizationPDF', true, ...
        'exportVisualizationPNG', true, ...
        'exportVisualizationPDFrootDirectory', exportVisualizationPDFrootDirectory, ...
        'exportVisualizationPDFdirectory', exportVisualizationPDFdirectory);
    
end
