%
% demoEngine.visualize.fancyMosaic
%
function fancyMosaic(theMRGCmosaic, ...
    thePSFatTheMosaicEccentricity, ...
    domainVisualizationLimits, ...
    domainVisualizationTicks, ...
    exportVisualizationPDFrootDirectory, ...
    exportVisualizationPDFdirectory)


    % Generate a PSF visualization data struct (containing the vLambda-weighted PSF) for
    % visualization purposes
    PSFvisualizationOffset = theMRGCmosaic.eccentricityDegs - [mean(domainVisualizationLimits(1:2)) mean(domainVisualizationLimits(3:4))];
    vLambdaWeightedPSF.data = RGCMosaicAnalyzer.compute.vLambdaWeightedPSF(thePSFatTheMosaicEccentricity);
    vLambdaWeightedPSF.supportXdegs = thePSFatTheMosaicEccentricity.supportX/60 - PSFvisualizationOffset(1);
    vLambdaWeightedPSF.supportYdegs = thePSFatTheMosaicEccentricity.supportY/60 - PSFvisualizationOffset(2);


    % Visualize the full mosaic of RF centers using a representation
    % like the representation used in visualizing
    % mosaics of RGCs in typical in-vitro experiments (e.g. by the Chichilnisky lab)
    minCenterConeWeight = mRGCMosaic.sensitivityAtPointOfOverlap;
    

    % Get ready for publication-quality visualization
    ff = PublicationReadyPlotLib.figureComponents('1x1 giant rectangular-double wide mosaic', ...
        'darkScheme', true);
    
    % Plot the mosaic of mRGC RF centers only
    hFig = figure(1); clf;
    theAxes = PublicationReadyPlotLib.generatePanelAxes(hFig,ff);
    ax = theAxes{1,1};
    
    tmp = ff.backgroundColor;
    ff.backgroundColor = ff.legendBackgroundColor;
    ff.legendBackgroundColor = tmp;
    
    theMRGCmosaic.visualize(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'identifyInputCones', false, ...
        'identifyPooledCones', false, ...
        'minConeWeightVisualized', minCenterConeWeight, ...
        'centerSubregionContourSamples', 32, ...
        'plottedRFoutlineFaceAlpha', 1.0, ...
        'plottedRFoutlineLineWidth', 1.0, ...
        'plottedRFoutlineFaceColor', [1 1 1], ...
        'plottedRFoutlineEdgeColor',  [0 0 0], ...
        'domainVisualizationLimits', domainVisualizationLimits, ...
        'domainVisualizationTicks', domainVisualizationTicks, ...
        'plotTitle', sprintf('min center weight visualized: %2.3f', minCenterConeWeight), ...
        'withFigureFormat', ff, ...
        'backgroundColor', ff.legendBackgroundColor, ...
        'clearAxesBeforeDrawing', false);
    hold(ax, 'on');

    % double rendering
    theMRGCmosaic.visualize(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'identifyInputCones', false, ...
        'identifyPooledCones', false, ...
        'minConeWeightVisualized', minCenterConeWeight, ...
        'centerSubregionContourSamples', 32, ...
        'plottedRFoutlineFaceAlpha', 0.5, ...
        'plottedRFoutlineLineWidth', 4.0, ...
        'plottedRFoutlineEdgeColor', [0 0 0], ...
        'plottedRFoutlineFaceColor',  [0. 1.0 0.0], ...
        'domainVisualizationLimits', domainVisualizationLimits, ...
        'domainVisualizationTicks', domainVisualizationTicks, ...
        'plotTitle', sprintf('min center weight visualized: %2.3f', minCenterConeWeight), ...
        'withFigureFormat', ff, ...
        'backgroundColor', ff.legendBackgroundColor, ...
        'clearAxesBeforeDrawing', false)
    
    theMRGCmosaic.visualize(...
        'figureHandle', hFig, ...
        'axesHandle', ax, ...
        'identifyInputCones', false, ...
        'identifyPooledCones', false, ...
        'minConeWeightVisualized', minCenterConeWeight, ...
        'centerSubregionContourSamples', 32, ...
        'plottedRFoutlineFaceAlpha', 0.0, ...
        'plottedRFoutlineLineWidth', 2, ...
        'plottedRFoutlineEdgeColor', [0 1 0 ], ...
        'plottedRFoutlineFaceColor',  [0. 1 0.0], ...
        'domainVisualizationLimits', domainVisualizationLimits, ...
        'domainVisualizationTicks', domainVisualizationTicks, ...
        'plotTitle', ' ', ...
        'withFigureFormat', ff, ...
        'backgroundColor', ff.legendBackgroundColor, ...
        'clearAxesBeforeDrawing', false, ...
        'visualizationPDFfileName', 'mRGCmosaic', ...
        'exportVisualizationPDF', true, ...
        'exportVisualizationPNG', true, ...
        'exportVisualizationPDFrootDirectory', exportVisualizationPDFrootDirectory, ...
        'exportVisualizationPDFdirectory', exportVisualizationPDFdirectory);
    
end
