%
% demoEngine.visualize.simulationAnimationsAndStaticRenderings
%
function simulationAnimationsAndStaticRenderings(theDataFileName, ...
    visualizeResponsesOfInputConesToRGCindex, ...
    theResponseBiasForPhotocurrentInnerRetinalFilterCascade, ...
    theResponseDelayForPhotocurrentInnerRetinalFilterCascade, ...
    maxTimeToVisualize, ...
    overlaySceneInsetOnTopOfRetinalImage, ...
    exportVisualizationRootDirectory, exportVisualizationPDFdirectory, ...
    exportVisualizationVideoDirectory, exportDataDirectory)
    
    % Load the data
    theDataFileName = fullfile(exportVisualizationRootDirectory, exportDataDirectory, theDataFileName);

    % Check to see if we have theMRGCmosaicResponseDictionary
    S = whos('-file', theDataFileName);
    foundIt = false;
    for iVar = 1:length(S)
        if (strcmp(S(iVar).name, 'theMRGCmosaicResponseDictionary'))
            foundIt = true;
        end
    end

    assert(foundIt, ...
        sprintf('No MRGCmosaic responses dictionary found in %s.\nHave you run the simulation with ''recomputeMRGCmosaicSimulation'' set to true?\n', theDataFileName));

    load(theDataFileName, ...
        'theMRGCmosaic', 'sceneCropParams', ...
        'theConeMosaicSpatioTemporalExcitationResponse', ...
        'theConeExcitationsResponseTemporalSupportSeconds', ...
        'theScene', 'theRetinalImage', 'theFixationalEMObj', ...
        'theConeMosaicSpatioTemporalPhotocurrentResponses', ...
        'thePhotocurrentResponseTemporalSupportSeconds', ...
        'theMRGCmosaicResponseDictionary');
    
    
    if (~overlaySceneInsetOnTopOfRetinalImage)
        theScene = [];
    end

    if (~isempty(visualizeResponsesOfInputConesToRGCindex))
        % Compute photocurrents for cone indices that provide input to a single mRGC
        targetMRGCindex = visualizeResponsesOfInputConesToRGCindex(1);

        surroundConnectivityVector = full(squeeze(theMRGCmosaic.rgcRFsurroundConeConnectivityMatrix(:, targetMRGCindex)));
        surroundConeIndices = find(surroundConnectivityVector > theMRGCmosaic.minSurroundWeightForInclusionInComputing);
        coneIndicesToVisualize = surroundConeIndices;
    else
        coneIndicesToVisualize = 1:theMRGCmosaic.inputConeMosaic.conesNum;
    end


    theMRGCmosaic.inputConeMosaic.visualize(...
        'labelConesWithIndices', coneIndicesToVisualize);


    thePDFfileName = 'mRGCresponseTraces.pdf';
    theVisualizedResponseDataSetLabels{1} = 'cone modulations + BK filters';
    theResponseBias(1) = 0;
    theResponseDelay(1) = 0;

    theVisualizedResponseDataSetLabels{2} = 'photocurrents + inner retina filter cascade';
    theResponseBias(2) = theResponseBiasForPhotocurrentInnerRetinalFilterCascade;
    theResponseDelay(2) = theResponseDelayForPhotocurrentInnerRetinalFilterCascade;

    
    c = brewermap(6, 'blues');
    theResonseColors(1,:) = c(6,:);
    c = brewermap(6, 'reds');
    theResonseColors(2,:) = c(6,:);
    c = brewermap(6, 'greens');
    theResonseColors(3,:) = c(6,:);

    demoEngine.visualize.responseTimeSeriesForSingleMRGC(targetMRGCindex, ...
        theMRGCmosaicResponseDictionary, theVisualizedResponseDataSetLabels, ...
        theResonseColors, ...
        theResponseBias, theResponseDelay, maxTimeToVisualize, ...
        exportVisualizationRootDirectory, exportVisualizationPDFdirectory, ...
        thePDFfileName);



    % Render video of everything
    demoEngine.visualize.simulationTimeCourse(...
        theMRGCmosaicResponseDictionary, targetMRGCindex, ...
        theMRGCmosaic.inputConeMosaic, ...
        theConeMosaicSpatioTemporalPhotocurrentResponses, ...
        thePhotocurrentResponseTemporalSupportSeconds, ...
        theResponseBias, theResponseDelay, ...
        theScene, theRetinalImage, theFixationalEMObj, ...
        exportVisualizationRootDirectory, ...
        exportVisualizationVideoDirectory, ...
        sprintf('photoCurrentsMovie.pdf'));

end


