%
% demoEngine.visualize.simulationAnimationsAndStaticRenderings
%
function simulationAnimationsAndStaticRenderings(theDataFileName, visualizeResponsesOfInputConesToRGCindex, ...
            overlaySceneInsetOnTopOfRetinalImage, ...
            exportVisualizationRootDirectory, exportVisualizationPDFdirectory, ...
            exportVisualizationVideoDirectory, exportDataDirectory)
    
    % Load the data
    theDataFileName = fullfile(exportVisualizationRootDirectory, exportDataDirectory, theDataFileName);
    load(theDataFileName, ...
        'theMRGCmosaic', 'sceneCropParams', ...
        'theConeMosaicSpatioTemporalExcitationResponse', ...
        'theConeExcitationsResponseTemporalSupportSeconds', ...
        'theScene', 'theRetinalImage', 'theFixationalEMObj', ...
        'theConeMosaicSpatioTemporalPhotocurrentResponses', ...
        'thePhotocurrentResponseTemporalSupportSeconds', ...
        'theMRGCmosaicResponseDictionary');
    
    
    if (~overlaySceneInsetOnTopOfRetinalImage)
        theScene = [];
    end

    if (~isempty(visualizeResponsesOfInputConesToRGCindex))
        % Compute photocurrents for cone indices that provide input to a single mRGC
        targetMRGCindex = visualizeResponsesOfInputConesToRGCindex(1);

        surroundConnectivityVector = full(squeeze(theMRGCmosaic.rgcRFsurroundConeConnectivityMatrix(:, targetMRGCindex)));
        surroundConeIndices = find(surroundConnectivityVector > theMRGCmosaic.minSurroundWeightForInclusionInComputing);
        coneIndicesToVisualize = surroundConeIndices;
    else
        coneIndicesToVisualize = 1:theMRGCmosaic.inputConeMosaic.conesNum;
    end


    theMRGCmosaic.inputConeMosaic.visualize(...
        'labelConesWithIndices', coneIndicesToVisualize);

    % Bias and delay to be applied to the photocurrent + inner retina
    % filter to visually align it to the cone excitations + B&K filter
    theResponseBias = 0.05;
    theResponseDelay = 10/1000;

    demoEngine.visualize.responseTimeSeriesForSingleMRGC(theMRGCmosaicResponseDictionary, targetMRGCindex, ...
        theResponseBias, theResponseDelay, ...
        exportVisualizationRootDirectory, exportVisualizationPDFdirectory, ...
        sprintf('mRGCresponseTraces_%1.0fCdM2.pdf', sceneCropParams.meanLuminanceCdM2));

    % Render video of everything
    demoEngine.visualize.simulationTimeCourse(...
        theMRGCmosaicResponseDictionary, targetMRGCindex, ...
        theMRGCmosaic.inputConeMosaic, ...
        theConeMosaicSpatioTemporalPhotocurrentResponses, ...
        thePhotocurrentResponseTemporalSupportSeconds, ...
        theResponseBias, theResponseDelay, ...
        theScene, theRetinalImage, theFixationalEMObj, ...
        exportVisualizationRootDirectory, ...
        exportVisualizationVideoDirectory, ...
        sprintf('photoCurrentsMovie_%1.0fCdM2.pdf', sceneCropParams.meanLuminanceCdM2));

end


