function t_contastConeExcitationVsPhotocurrentSTFs(options)
% Examples used to generate material for the VSS2026 talk

% History:
%    03/20/26  NPC  Wrote it.

% Examples:
%{

    % Key params: (1) temporal frequency
    stimulus_TF_Hz = 2.5;

    % Key params: (2) mean luminance
    meanLuminanceCdM2 = 100;


    CRT_refresh_Hz = 150;    
    spatialPhaseIncrementDegsOptimal = 360 / (CRT_refresh_Hz / stimulus_TF_Hz)
    spatialPhaseIncrementDegs = 12

    framesNumPerPeriod = 360/ spatialPhaseIncrementDegs;
    frameDurationSeconds = (1/stimulus_TF_Hz)/framesNumPerPeriod;
    pCurrentTemporalResolutionSeconds = 3.0/1000;

    photocurrentParams = struct(...
        'osBiophysicalModelWarmUpTimeSeconds', 1, ...
        'osBiophysicalModelTemporalResolutionSeconds', 1.0000e-05, ...
        'temporalResolutionSeconds', pCurrentTemporalResolutionSeconds);

    % Trying to match stated contrasts of Lee&Shapley, who claim 35% and 37% L/M cone contrasts, 60 for achromatic)
    stimContrast = containers.Map();
    stimContrast('Achromatic') = 0.60;
    stimContrast('LconeIsolating') = 0.25;   % MAX ACHIEVABLE L-cone isolating ON 'CRT-Sony-HorwitzLab', which is a SONY CRT, like Lee et al
    stimContrast('MconeIsolating') = 0.33;   % MAX ACHIEVABLE M-cone isolating ON 'CRT-Sony-HorwitzLab', which is a SONY CRT, like Lee et al

    % Select which chromaticity to run
    stimulusChroma = 'Achromatic';
    %stimulusChroma = 'MconeIsolating';

    extraInfoEncodedInFileName = sprintf('%1.1fHz_%2.0fCDM2_%2.0f%%', stimulus_TF_Hz, meanLuminanceCdM2, 100*stimContrast(stimulusChroma));

    t_mRGCMosaicSTFcomputation(...
        'rgcMosaicName', 'PLOSpaperNasal2DegsTinyMosaic', ...
        'opticsSubjectName', 'PLOSpaperDefaultSubject', ...
        'targetVisualSTFdescriptor', 'default', ...
        'cropParams', struct(...
            'eccentricityDegs', [2 0], ...
            'sizeDegs', [0.5 0.5] ...
        ), ...
        'opticsForSTFresponses', struct(...
            'type', 'refractionResidualWithRespectToNativeOptics',...
            'refractiveErrorDiopters', 0.0 ...
        ), ...
        'STFchromaticity', stimulusChroma, ...
        'STFcontrast', stimContrast(stimulusChroma), ...
        'STForientationDeltaDegs', 90, ...                          % every 90 degs
        'STFtemporalFrequencyHz', stimulus_TF_Hz, ...                          
        'STFsfSupport', logspace(log10(0.1), log10(20), 8), ...    
        'STFmeanLuminanceCdM2', meanLuminanceCdM2, ...              
        'STFbackgroundXYchromaticity', [0.436, 0.476], ...          
        'displayType', 'CRT-Sony-HorwitzLab', ...                   % SONY monitor like Lee & Shapley 2012
        'displayLuminanceHeadroomPercentage', 200/100, ...          % Very large luminance headroom to generate these high cone contrasts
        'spatialPhaseIncrementDegs', spatialPhaseIncrementDegs, ... % Optimal for the 150 Hz CRT of Lee&Shapley 2012. Their 2.5 Hz stimulus would correspond to 6 degs.
        'coneFundamentalsOptimizedForStimPosition', true, ...
        'photocurrentParams', photocurrentParams, ...
        'extraInfoEncodedInFileName', extraInfoEncodedInFileName, ...  %
        'computeInputConeMosaicResponses', true, ...                            % computation stage 1
        'computeInputConeMosaicResponsesBasedOnConeExcitations', ~true, ...     % computation sub-stage 1A: compute the cone excitations
        'computeInputConeMosaicResponsesBasedOnPhotocurrents',  true, ...       % computation sub-stage 1B: compute the photocurrents
        'visualizeMosaicResponses', ~true, ...                                  % set this to true to visualize the dynamic cone mosaic response during step 1A
        'inspectInputConeMosaicResponses', ~true, ...                           % computation sub-stage 1C: visualize exemplar cone excitation & photocurrent responses
        'computeMRGCMosaicResponses', ~true, ...                                % computation stage 2:  compute the mRGC responses
        'visualizeSinusoidalFitsForPhotocurrentBasedMRGCresponses', ~true, ...
        'visualizeConeExcitationVsPhotocurrentSTFs', ~true, ...
        'analyzeSTFresponsesForTargetCells', ~true ,...                         % compute the STFs
        'contrastBPIsOfConeIsolatingVsAchromaticSTFs', ~true ...                % contrast the BPIs of coneIsolating vs achromatic STFs
    );


    % ---- Example 1 ----

    % Key params: (1) temporal frequency
    stimulusTFHz = 2.5;

    % Key params: (2) mean luminance
    meanLuminanceCdM2 = 100;

    % Key params: (3) contrast
    stimContrast = 0.5;

    sfSupport = logspace(log10(0.1), log10(20), 8);

    stimChromaticity = 'Achromatic';
    
    % For Lee et al:
    %stimContrast('Achromatic') = 0.60;
    %stimContrast('LconeIsolating') = 0.25;   % MAX ACHIEVABLE L-cone isolating ON 'CRT-Sony-HorwitzLab', which is a SONY CRT, like Lee et al
    %stimContrast('MconeIsolating') = 0.33;   % MAX ACHIEVABLE M-cone isolating ON 'CRT-Sony-HorwitzLab', which is a SONY CRT, like Lee et al

    

    CRTrefreshHz = 150;    
    % Optimal for the 150 Hz CRT of Lee&Shapley 2012. Their 2.5 Hz stimulus would correspond to 6 degs.
    spatialPhaseIncrementDegsOptimal = 360 / (CRTrefreshHz / stimulusTFHz)
    spatialPhaseIncrementDegs = 12
    

    framesNumPerPeriod = 360/ spatialPhaseIncrementDegs;
    frameDurationSeconds = (1/stimulusTFHz)/framesNumPerPeriod;
    pCurrentTemporalResolutionSeconds = 3.0/1000;

    photocurrentParams = struct(...
        'osBiophysicalModelWarmUpTimeSeconds', 1, ...
        'osBiophysicalModelTemporalResolutionSeconds', 1.0000e-05, ...
        'temporalResolutionSeconds', pCurrentTemporalResolutionSeconds);


    % Extra string to be added to the generated response filenames so as to encode
    % stimulus TF, mean luminance and contrast, 
    % which are the parameters we want to examine the effect on the computed STFs
    
    extraInfoEncodedInFileName = sprintf('%1.1fHz_%2.0fCDM2_%2.0f%%', stimulusTFHz, meanLuminanceCdM2, stimContrast);


    % Actions to perform
    computeInputConeMosaicResponses = true;                             % computation stage 1
    computeInputConeMosaicResponsesBasedOnConeExcitations =~true;       % computation sub-stage 1A: compute the cone excitations
    computeInputConeMosaicResponsesBasedOnPhotocurrents = true;         % computation sub-stage 1B: compute the photocurrents
    
    visualizeMosaicResponses = ~true;                                   % set this to true to visualize the dynamic cone mosaic response during step 1A
    inspectInputConeMosaicResponses = ~true;                            % computation sub-stage 1C: visualize exemplar cone excitation & photocurrent responses
    
    computeMRGCMosaicResponses = ~true;                                 % computation stage 2:  compute the mRGC responses
    visualizeSinusoidalFitsForPhotocurrentBasedMRGCresponses = ~true;
   
    analyzeSTFresponsesForTargetCells = ~true;                          % compute the STFs
    visualizeConeExcitationVsPhotocurrentSTFs = ~true;


    t_contastConeExcitationVsPhotocurrentSTFs(...
        'STFtemporalFrequencyHz', stimulusTFHz, ...
        'STFmeanLuminanceCdM2', meanLuminanceCdM2, ...
        'STFchromaticity', stimChromaticity, ...
        'STFcontrast', stimContrast, ...
        'STFsfSupport', sfSupport, ...
        'spatialPhaseIncrementDegs', spatialPhaseIncrementDegs, ...
        'photocurrentParams', photocurrentParams, ...
        'extraInfoEncodedInFileName', extraInfoEncodedInFileName, ...
        'computeInputConeMosaicResponses', computeInputConeMosaicResponses, ...
        'computeInputConeMosaicResponsesBasedOnConeExcitations',computeInputConeMosaicResponsesBasedOnConeExcitations, ...
        'computeInputConeMosaicResponsesBasedOnPhotocurrents', computeInputConeMosaicResponsesBasedOnPhotocurrents, ...
        'visualizeMosaicResponses', visualizeMosaicResponses, ...      
        'inspectInputConeMosaicResponses', inspectInputConeMosaicResponses, ...
        'computeMRGCMosaicResponses', computeMRGCMosaicResponses, ...  
        'visualizeSinusoidalFitsForPhotocurrentBasedMRGCresponses',visualizeSinusoidalFitsForPhotocurrentBasedMRGCresponses, ...
        'analyzeSTFresponsesForTargetCells',analyzeSTFresponsesForTargetCells, ...
        'visualizeConeExcitationVsPhotocurrentSTFs', visualizeConeExcitationVsPhotocurrentSTFs ...
    );


    % ----- Example 2 ----
    cropParams =  struct(...
            'eccentricityDegs', [2 0], ...
            'sizeDegs', [0.5 0.5] ...
        );

    opticsForSTFresponses = struct(...
            'type', 'refractionResidualWithRespectToNativeOptics',...
            'refractiveErrorDiopters', 0.20 ...
        );

    t_contastConeExcitationVsPhotocurrentSTFs(...
        'cropParams', cropParams, ...
        'opticsForSTFresponses, opticsForSTFresponses);
%}

arguments

    % ---- Mosaic specifiers for selecting a prebaked mRGC mosaic ------
    
    % See RGCMosaicConstructor.helper.utils.initializeRGCMosaicGenerationParameters
    % for what is available and to add new mosaics
    options.rgcMosaicName (1,:) char = 'PLOSpaperNasal2DegsTinyMosaic';


    % ---- Which species to employ ----
    % Choose between {'macaque', 'human'}. If 'macaque' is chosen, the input
    % cone mosaic has a 1:1 L/M cone ratio.
    options.coneMosaicSpecies  (1,:) char {mustBeMember(options.coneMosaicSpecies,{'human','macaque'})} = 'human';


    % ----- Which subject optics to employ -----
    options.opticsSubjectName (1,:) ...
        char ...
        {...
        mustBeMember(options.opticsSubjectName, ...
            { ...
            'PLOSpaperDefaultSubject' ...
            'PLOSpaperSecondSubject' ...
            'VSS2024TalkFirstSubject' ...
            'VSS2024TalkSecondSubject' ...
            'PLOSpaperStrehlRatio_0.87' ...
            'PLOSpaperStrehlRatio_0.72' ...
            'PLOSpaperStrehlRatio_0.59' ...
            'PLOSpaperStrehlRatio_0.60' ...
            'PLOSpaperStrehlRatio_0.27' ...
            'PLOSpaperStrehlRatio_0.23' ...
            'PLOSpaperStrehlRatio_0.21' ...
            'PLOSpaperStrehlRatio_0.19' ...
            'PLOSpaperStrehlRatio_0.09' ...
            } ...
            ) ...
        } ...
        = 'PLOSpaperDefaultSubject';


    % ------ targetVisualSTF options ----
    % Options are : {'default', 'x1.3 RsRcRatio'}
    % These are with respect to the macaque data of the Croner & Kaplan '95 study
    % 'default': target the mean Rs/Rc, and the mean Ks/Kc (Rs/Rc)^2
    % See RGCMosaicConstructor.helper.surroundPoolingOptimizerEngine.generateTargetVisualSTFmodifiersStruct
    % for all existing options
    options.targetVisualSTFdescriptor (1,:) char = 'default';

    % Submosaic to map
    options.cropParams = [];

    % Different options for the optics
    options.opticsForSTFresponses = [];

    % STF params
    options.STFmeanLuminanceCdM2 (1,1) double = 100;
    options.STFbackgroundXYchromaticity (1,2) double = [0.436, 0.476];
    options.STFchromaticity (1,:) char{mustBeMember(options.STFchromaticity, {'LconeIsolating' 'MconeIsolating' 'Achromatic'})} = 'Achromatic';
    options.STFsfSupport (1,:) double = logspace(log10(0.05), log10(50), 15);
    options.STFtemporalFrequencyHz (1,1) double = 10;
    options.STFcontrast (1,1) double = 0.5;
    options.STForientationDeltaDegs (1,1) double = 90;

    options.extraInfoEncodedInFileName (1,:) char = '';

    options.displayType (1,:) char = 'CRT-Sony-HorwitzLab';
    options.displayLuminanceHeadroomPercentage (1,1) double = 200/100;
    options.coneFundamentalsOptimizedForStimPosition (1,1) logical = false;

    % Photocurrent (full biophysical model) params
    options.photocurrentParams (1,1) = struct(...
        'osBiophysicalModelWarmUpTimeSeconds',  1.0, ...
        'osBiophysicalModelTemporalResolutionSeconds',  1e-5, ...
        'temporalResolutionSeconds',  5/1000);

    % Decreasing the spatial phase increment results in higher temporal resolution, and vice versa
    options.spatialPhaseIncrementDegs (1,1) double = 30;

    % Visualizations
    options.visualizeStimulusSequence (1,1) logical = false;

    % Whether to visualize exemplar cone excitation & photocurrent responses
    options.inspectInputConeMosaicResponses (1,1) logical = false;

    % set this to true to visualize the dynamic cone mosaic response during step 1A
    options.visualizeMosaicResponses (1,1) logical = false;

    options.visualizeSinusoidalFitsForPhotocurrentBasedMRGCresponses (1,1) logical = false;
    options.visualizeConeExcitationVsPhotocurrentSTFs (1,1) logical = false;

    % ---- Choices of actions to perform ----

    % Whether to compute the input cone mosaic STF responses (stage 1)
    options.computeInputConeMosaicResponses (1,1) logical = false;

    % Whether to compute the cone excitations-based input cone mosaic STF responses 
    % (computation sub-stage 1A)
    options.computeInputConeMosaicResponsesBasedOnConeExcitations (1,1) logical = false;

    % Whether to compute the photocurrents-based input cone mosaic STF responses
    % (computation sub-stage 1B)
    options.computeInputConeMosaicResponsesBasedOnPhotocurrents (1,1) logical = false;

    % Whether to compute the mRGC mosaic STF responses
    % (computation stage 2)
    options.computeMRGCMosaicResponses (1,1) logical = false;
    
    % Whether to analyze the STF responses for select target mRGCs
    options.analyzeSTFresponsesForTargetCells(1,1) logical = false;
end % arguments
   

t_mRGCMosaicSTFcomputation(...
    'rgcMosaicName', options.rgcMosaicName, ...
    'coneMosaicSpecies', options.coneMosaicSpecies, ...
    'opticsSubjectName', options.opticsSubjectName, ...
    'targetVisualSTFdescriptor', options.targetVisualSTFdescriptor, ...
    'cropParams', options.cropParams, ...
    'opticsForSTFresponses', options.opticsForSTFresponses, ...
    'STFchromaticity', options.STFchromaticity, ...
    'STFcontrast', options.STFcontrast, ...
    'STForientationDeltaDegs', options.STForientationDeltaDegs, ...  
    'STFtemporalFrequencyHz', options.STFtemporalFrequencyHz, ...                          
    'STFsfSupport', logspace(log10(0.1), log10(20), 8), ...    
    'STFmeanLuminanceCdM2', options.STFmeanLuminanceCdM2, ...              
    'STFbackgroundXYchromaticity', options.STFbackgroundXYchromaticity, ...          
    'displayType', options.displayType, ...                   
    'displayLuminanceHeadroomPercentage', 200/100, ...         
    'spatialPhaseIncrementDegs', options.spatialPhaseIncrementDegs, ... 
    'coneFundamentalsOptimizedForStimPosition', options.coneFundamentalsOptimizedForStimPosition, ...
    'photocurrentParams', options.photocurrentParams, ...
    'extraInfoEncodedInFileName', options.extraInfoEncodedInFileName, ...  
    'computeInputConeMosaicResponses', options.computeInputConeMosaicResponses, ...                        
    'computeInputConeMosaicResponsesBasedOnConeExcitations', options.computeInputConeMosaicResponsesBasedOnConeExcitations, ...
    'computeInputConeMosaicResponsesBasedOnPhotocurrents',  options.computeInputConeMosaicResponsesBasedOnPhotocurrents, ...
    'visualizeMosaicResponses', options.visualizeMosaicResponses, ...                                  
    'inspectInputConeMosaicResponses', options.inspectInputConeMosaicResponses, ...                           
    'computeMRGCMosaicResponses', options.computeMRGCMosaicResponses, ...                       
    'visualizeSinusoidalFitsForPhotocurrentBasedMRGCresponses', false, ...
    'visualizeConeExcitationVsPhotocurrentSTFs', options.visualizeConeExcitationVsPhotocurrentSTFs, ...
    'analyzeSTFresponsesForTargetCells', options.analyzeSTFresponsesForTargetCells ...
);