function t_mRGCMosaicNonLinearities(options)
% Ispect the effect of different properties of the modified Naka-Rusthon output nonlinearity
%
% Description:
%   Ispect the effect of different properties of the modified Naka-Rusthon output nonlinearity
%   by visualizing the cone modulation- and photocurrent-based mRGC response to a single drifting grating
%
% History:
%    11/19/25  NPC  Wrote it.
%
% Examples:
%{

    % Basic call to compute the input cone mosaic responses (cone
    excitations + photocurrents based)
    t_mRGCMosaicNonLinearities();

    % Basic call to compute the mRGC mosaic responses to both types of
    % input cone mosaic responses (without static nonlinearities)
    t_mRGCMosaicNonLinearities(...
        'computeInputConeMosaicResponses', true, ...
        'computeMRGCMosaicResponses', ~true);


    % Basic call to only visualize previously computed mRGC responses 
    t_mRGCMosaicNonLinearities(...
        'computeInputConeMosaicResponses', false, ...
        'computeMRGCMosaicResponses', false, ...
        'onlyVisualizeMRGCresponses', true);


    % Background params
    backgroundLuminanceCdM2 = 200;
    adjustBackgroundChromaticityToEqualizeLandMconeExcitations = true;

    chromaticity = 'Achromatic';
    contrast = 0.5;
    temporalFrequencyHz = 0.2;
    orientationsDegs = 0;
    spatialFrequencyCPD = 3.0;

    t_mRGCMosaicNonLinearities( ...
        'backgroundLuminanceCdM2', backgroundLuminanceCdM2, ...
        'adjustBackgroundChromaticityToEqualizeLandMconeExcitations', adjustBackgroundChromaticityToEqualizeLandMconeExcitations, ...
        'chromaticity', chromaticity, ...
        'contrast', contrast, ...
        'temporalFrequencyHz', temporalFrequencyHz, ...
        'orientationsDegs', orientationsDegs, ...
        'spatialFrequencyCPD', spatialFrequencyCPD, ...
        'computeInputConeMosaicResponses', true, ...
        'computeInputConeMosaicResponsesBasedOnConeExcitations', ~true, ...
        'computeInputConeMosaicResponsesBasedOnPhotocurrents', ~true, ...
        'computeMRGCMosaicResponses', ~true);


    % The Naka-Rushton NL does the following:
    % Rrectified = HalfWaveRectifier(Rin-RinHalfWaveRectifierThreshold);
    % Rsn = Rrectified^(n*s);
    % R50sn = Rin50^(n*s)
    % Rout = Rrectified^(n) / (Rsn + R50sn);
    % Rout = Rout * prctile(Rrectified,RoutGainAdjustmentPercentile)/prctile(Rout,RoutGainAdjustmentPercentile);

    coneModulationsR50 = 0.5;
    coneModulationHalfWaveRectifierThreshold = -0.1;
    coneModulationsResponseBasedNonLinearitiesList{1} = struct(...
        'sourceSignal', 'compositeResponse', ...       % where to apply the non-linerity. choose from {'centerComponentResponse', 'surroundComponentResponse', 'compositeResponse'}
        'type', 'Naka Rushton', ...
        'params', struct(...
            'RinHalfWaveRectifierThreshold', coneModulationHalfWaveRectifierThreshold, ...   % H-W rectifier threshold (in cone modulations units)
            'Rin50', coneModulationsR50, ...            % semi-saturation response (in normalized range, based on the passed RinNormalizer)
            'n', 3.0, ...                               % exponent
            's', 1.0, ...                                % super-saturation exponent (super-saturating if s > 1)
            'RoutGainAdjustmentPercentile', 100 ...
        ) ...
    );

    photocurrentR50 = 5;
    photocurrentHalfWaveRectifierThreshold = -3.0
    photocurrentsResponseBasedNonLinearitiesList{1} = struct(...
        'sourceSignal', 'compositeResponse', ...        % where to apply the non-linerity. choose from {'centerComponentResponse', 'surroundComponentResponse', 'compositeResponse'}
        'type', 'Naka Rushton', ...
        'params', struct(...
            'RinHalfWaveRectifierThreshold', photocurrentHalfWaveRectifierThreshold, ... % H-W rectifier threshold (in photocurrent units)
            'Rin50', photocurrentR50, ...               % semi-saturation response (in photocurrent units)
            'n', 3.0, ...                               % exponent
            's', 1.0, ...                                % super-saturation exponent (super-saturating if s > 1)
            'RoutGainAdjustmentPercentile', 95 ...
        ) ...
    );


    coneModulationsBasedNonLinearityParamsStruct = struct(...
        'label', 'noSatNL', ...     % some string encoding the non-linear processing; it is encoded in the output filename
        'nonLinearitiesList', coneModulationsResponseBasedNonLinearitiesList ...
    );

    photocurrentsBasedNonLinearityParamsStruct = struct(...
        'label', coneExcitationsBasedNonLinearityParamsStruct.label, ...
        'nonLinearitiesList', photocurrentsResponseBasedNonLinearitiesList ...
    );


    t_mRGCMosaicNonLinearities(...
        'computeInputConeMosaicResponses', false, ...
        'computeMRGCMosaicResponses', true, ...
        'coneModulationsBasedNonLinearityParamsStruct', coneModulationsBasedNonLinearityParamsStruct, ...
        'photocurrentsBasedNonLinearityParamsStruct', photocurrentsBasedNonLinearityParamsStruct ...
    );

    t_mRGCMosaicNonLinearities( ...
        'backgroundLuminanceCdM2', backgroundLuminanceCdM2, ...
        'adjustBackgroundChromaticityToEqualizeLandMconeExcitations', adjustBackgroundChromaticityToEqualizeLandMconeExcitations, ...
        'chromaticity', chromaticity, ...
        'contrast', contrast, ...
        'temporalFrequencyHz', temporalFrequencyHz, ...
        'orientationsDegs', orientationsDegs, ...
        'spatialFrequencyCPD', spatialFrequencyCPD, ...
        'computeInputConeMosaicResponses', true, ...
        'computeInputConeMosaicResponsesBasedOnConeExcitations', ~true, ...
        'computeInputConeMosaicResponsesBasedOnPhotocurrents', ~true, ...
        'computeMRGCMosaicResponses', true, ...
        'coneModulationsBasedNonLinearityParamsStruct', coneModulationsBasedNonLinearityParamsStruct, ...
        'photocurrentsBasedNonLinearityParamsStruct', photocurrentsBasedNonLinearityParamsStruct);


%}

arguments

    % ---- Mosaic specifiers for selecting a prebaked mRGC mosaic ------
    
    % See RGCMosaicConstructor.helper.utils.initializeRGCMosaicGenerationParameters
    % for what is available and to add new mosaics
    options.rgcMosaicName (1,:) char = 'JCNpaperNasal2DegsTinyMosaic';


    % ---- Which species to employ ----
    % Choose between {'macaque', 'human'}. If 'macaque' is chosen, the input
    % cone mosaic has a 1:1 L/M cone ratio.
    options.coneMosaicSpecies  (1,:) char {mustBeMember(options.coneMosaicSpecies,{'human','macaque'})} = 'human';


    % ----- Which subject optics to employ -----
    options.opticsSubjectName (1,:) ...
        char ...
        {...
        mustBeMember(options.opticsSubjectName, ...
            { ...
            'JCNpaperDefaultSubject' ...
            'JCNpaperSecondSubject' ...
            'VSS2024TalkFirstSubject' ...
            'VSS2024TalkSecondSubject' ...
            'JCNpaperStrehlRatio_0.87' ...
            'JCNpaperStrehlRatio_0.72' ...
            'JCNpaperStrehlRatio_0.59' ...
            'JCNpaperStrehlRatio_0.60' ...
            'JCNpaperStrehlRatio_0.27' ...
            'JCNpaperStrehlRatio_0.23' ...
            'JCNpaperStrehlRatio_0.21' ...
            'JCNpaperStrehlRatio_0.19' ...
            'JCNpaperStrehlRatio_0.09' ...
            } ...
            ) ...
        } ...
        = 'JCNpaperDefaultSubject';


    % ------ targetVisualSTF options ----
    % Options are : {'default', 'x1.3 RsRcRatio'}
    % These are with respect to the macaque data of the Croner & Kaplan '95 study
    % 'default': target the mean Rs/Rc, and the mean Ks/Kc (Rs/Rc)^2
    % See RGCMosaicConstructor.helper.surroundPoolingOptimizerEngine.generateTargetVisualSTFmodifiersStruct
    % for all existing options
    options.targetVisualSTFdescriptor (1,:) char = 'default';

    % Submosaic to map
    options.cropParams = [];

    % Different options for the optics
    options.opticsForResponses = [];

    % Background luminance and chromaticity
    options.backgroundLuminanceCdM2 (1,1) double = 100;
    options.backgroundChromaticity (1,2) double = [0.31, 0.31];
    options.adjustBackgroundChromaticityToEqualizeLandMconeExcitations (1,1) logical = false;

    % Stimulus chromaticity and contrast
    options.chromaticity (1,:) char{mustBeMember(options.chromaticity, {'LconeIsolating' 'MconeIsolating' 'SconeIsolating', 'Achromatic'})} = 'Achromatic';
    options.contrast (1,1) double = 1.0;

    % Temporal frequency
    options.temporalFrequencyHz (1,1) double = 4;
    
    % Decreasing the spatial phase increment results in higher temporal resolution, and vice versa
    options.spatialPhaseIncrementDegs (1,1) double = 30;

    % Orientation and spatial frequency
    options.orientationsDegs (1,1) double = 0;
    options.spatialFrequencyCPD (1,1) double = 3.0;

    % Photocurrent (full biophysical model) params
    options.photocurrentParams (1,1) = struct(...
        'osBiophysicalModelWarmUpTimeSeconds',  1.0, ...
        'osBiophysicalModelTemporalResolutionSeconds',  1e-5, ...
        'temporalResolutionSeconds',  5/1000);

    % Nonlinearities
    options.coneModulationsBasedNonLinearityParamsStruct = [];
    options.photocurrentsBasedNonLinearityParamsStruct = [];

    
    % Visualizations
    options.debugInputConeMosaicResponse (1,1) logical = false;
    options.debugStimulusSequence (1,1) logical = false;
    options.onlyVisualizeMRGCresponses (1,1) logical = false;

    % ---- Choices of actions to perform ----
    % Whether to compute the input cone mosaic STF responses
    options.computeInputConeMosaicResponses (1,1) logical = true;
    options.computeInputConeMosaicResponsesBasedOnConeExcitations (1,1) logical = true;
    options.computeInputConeMosaicResponsesBasedOnPhotocurrents (1,1) logical = true;

    % Whether to compute the input cone mosaic STF responses
    options.computeMRGCMosaicResponses (1,1) logical = false;
    
    % Whether to close previously open figures
    options.closePreviouslyOpenFigures (1,1) logical = true;

end % arguments



% Set flags from key/value pairs

% Mosaic specifiers for selecting a previously synthesized center-connected mRGC mosaic 
rgcMosaicName = options.rgcMosaicName;
coneMosaicSpecies = options.coneMosaicSpecies;
opticsSubjectName = options.opticsSubjectName;
targetVisualSTFdescriptor = options.targetVisualSTFdescriptor;

% Optics to employ for the computations
opticsForResponses = options.opticsForResponses;

% Backgound luminance and chromaticity
backgroundLuminanceCdM2 = options.backgroundLuminanceCdM2;
backgroundChromaticity = options.backgroundChromaticity;
adjustBackgroundChromaticityToEqualizeLandMconeExcitations = options.adjustBackgroundChromaticityToEqualizeLandMconeExcitations;

% Stimulus chromaticity and contrast
chromaticity = options.chromaticity; 
contrast = options.contrast;

% Temporal frequency
temporalFrequencyHz = options.temporalFrequencyHz;

% Spatial params
spatialPhaseIncrementDegs = options.spatialPhaseIncrementDegs;
orientationsDegs = options.orientationsDegs;
spatialFrequencyCPD = options.spatialFrequencyCPD;

% Photocurrent params
photocurrentParams = options.photocurrentParams;

% Nonlinearities
coneModulationsBasedNonLinearityParamsStruct = options.coneModulationsBasedNonLinearityParamsStruct;
photocurrentsBasedNonLinearityParamsStruct = options.photocurrentsBasedNonLinearityParamsStruct;


% Mosaic cropping
cropParams = options.cropParams;

% Visualizations
debugInputConeMosaicResponse = options.debugInputConeMosaicResponse;
debugStimulusSequence = options.debugStimulusSequence;
onlyVisualizeMRGCresponses = options.onlyVisualizeMRGCresponses;

% Actions to perform
computeInputConeMosaicResponses = options.computeInputConeMosaicResponses;
computeInputConeMosaicResponsesBasedOnConeExcitations = options.computeInputConeMosaicResponsesBasedOnConeExcitations;
computeInputConeMosaicResponsesBasedOnPhotocurrents = options.computeInputConeMosaicResponsesBasedOnPhotocurrents;
computeMRGCMosaicResponses = options.computeMRGCMosaicResponses;


% Load the mRGCmosaic specified by the passed parameters:
% coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor
% and generate the optics that were used to synthesize the mosaic
[theMRGCmosaic, theOI, thePSFatTheMosaicEccentricity, ...
    prebakedMRGCMosaicDir, prebakedMRGCMosaicFilename] = mRGCMosaic.loadPrebakedMosaic(...
        coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor, ...
        'computeTheMosaicOptics', true, ...
        'opticsToEmploy', opticsForResponses, ...
        'cropParams', cropParams);


% Filenames for intermediate responses
intermediateDataDir = RGCMosaicConstructor.filepathFor.intermediateDataDir();

% Directory of intermediateDataDir where all computed data will go
subDir = 'nonLinearityDemos';

figureDir = fullfile(isetbioRootPath,'local',mfilename);
if (~exist(figureDir,'dir'))
    mkdir(figureDir);
end
fprintf('Will save figures/videos into %s\n',figureDir);


[theInputConeMosaicResponsesFullFileName, theMRGCMosaicResponsesFullFileName] = computeSimulationForCurrentStimulus(...
    orientationsDegs, spatialFrequencyCPD, ...
    chromaticity, contrast, ...
    backgroundChromaticity, backgroundLuminanceCdM2, ...
    adjustBackgroundChromaticityToEqualizeLandMconeExcitations, ...
    spatialPhaseIncrementDegs, temporalFrequencyHz, ...
    prebakedMRGCMosaicFilename, intermediateDataDir, subDir, figureDir, ...
    opticsForResponses, theOI, thePSFatTheMosaicEccentricity, ...
    photocurrentParams, ...
    theMRGCmosaic, ...
    coneModulationsBasedNonLinearityParamsStruct, ...
    photocurrentsBasedNonLinearityParamsStruct, ...
    computeInputConeMosaicResponses, ...
    computeInputConeMosaicResponsesBasedOnConeExcitations, ...
    computeInputConeMosaicResponsesBasedOnPhotocurrents, ...
    computeMRGCMosaicResponses, ...
    onlyVisualizeMRGCresponses, ...
    debugInputConeMosaicResponse, debugStimulusSequence);


end


function [theInputConeMosaicResponsesFullFileName, theMRGCMosaicResponsesFullFileName] = computeSimulationForCurrentStimulus(...
    orientationsDegs, spatialFrequencyCPD, ...
    chromaticity, contrast, ...
    backgroundChromaticity, backgroundLuminanceCdM2, ...
    adjustBackgroundChromaticityToEqualizeLandMconeExcitations, ...
    spatialPhaseIncrementDegs, temporalFrequencyHz, ...
    prebakedMRGCMosaicFilename, intermediateDataDir, subDir, figureDir, ...
    opticsForResponses, theOI, thePSFatTheMosaicEccentricity, ...
    photocurrentParams, ...
    theMRGCmosaic, ...
    coneModulationsBasedNonLinearityParamsStruct, ...
    photocurrentsBasedMRGCNonLinearityParamsStruct, ...
    computeInputConeMosaicResponses, ...
    computeInputConeMosaicResponsesBasedOnConeExcitations, ...
    computeInputConeMosaicResponsesBasedOnPhotocurrents, ...
    computeMRGCMosaicResponses, ...
    onlyVisualizeMRGCresponses, ...
    debugInputConeMosaicResponse, debugStimulusSequence)

    % Encode chromaticity, eccentricity and size of the mosaic
    postFix = sprintf('%s@%2.0f_%2.0fCd_%.0fDeg_%.1fCpD_%2.0fHz_%s_Ecc_%2.1f_%2.1f_Size_%2.1f_%2.1f', ...
        chromaticity, ...
        contrast*100, ...
        backgroundLuminanceCdM2, ...
        orientationsDegs, ...
        spatialFrequencyCPD, ...
        temporalFrequencyHz, ...
        strrep(prebakedMRGCMosaicFilename, '.mat', ''), ...
        theMRGCmosaic.eccentricityDegs(1), ...
        theMRGCmosaic.eccentricityDegs(2), ...
        theMRGCmosaic.sizeDegs(1), ...
        theMRGCmosaic.sizeDegs(2));
   

    theInputConeMosaicResponsesFileName = fullfile(subDir, sprintf('coneResponses_%s.mat', postFix));
    theInputConeMosaicResponsesFullFileName = RGCMosaicConstructor.filepathFor.augmentedPathWithSubdirs(...
            intermediateDataDir, theInputConeMosaicResponsesFileName, ...
            'generateMissingSubDirs', true);

    theMRGCMosaicResponsesFileName = fullfile(subDir, sprintf('mRGCResponses_%s.mat', postFix));
    theMRGCMosaicResponsesFullFileName = RGCMosaicConstructor.filepathFor.augmentedPathWithSubdirs(...
            intermediateDataDir, theMRGCMosaicResponsesFileName, ...
            'generateMissingSubDirs', true);


    if (~isempty(coneModulationsBasedNonLinearityParamsStruct))
        theMRGCMosaicResponsesFullFileName = ...
            strrep(theMRGCMosaicResponsesFullFileName, 'Responses', sprintf('Responses_%s', coneModulationsBasedNonLinearityParamsStruct.label));
    elseif (~isempty(photocurrentsBasedMRGCNonLinearityParamsStruct))
        theMRGCMosaicResponsesFullFileName = ...
            strrep(theMRGCMosaicResponsesFullFileName, 'Responses', sprintf('Responses_%s', photocurrentsBasedMRGCNonLinearityParamsStruct.label));
    end


    % Compute input cone mosaic response
    if (computeInputConeMosaicResponses) && (computeInputConeMosaicResponsesBasedOnConeExcitations)

        % Form stimParams struct
        switch (chromaticity)
            case 'LconeIsolating'
                coneContrastDirection = [1 0 0];
            case 'MconeIsolating'
                coneContrastDirection = [0 1 0];
            case 'SconeIsolating'
                coneContrastDirection = [0 0 1];
            case 'Achromatic'
                coneContrastDirection = [1 1 1];
        end

        opticsIsDiffractionLimited = false;
        if (~isempty(opticsForResponses)) && (isstruct(opticsForResponses) && (isfield(opticsForResponses, 'type'))) && ...
           ((strcmp(opticsForResponses.type, 'adaptiveOptics6MM')) || (strcmp(opticsForResponses.type, 'adaptiveOptics6MMwithLCA')))
                opticsIsDiffractionLimited = true;
        end

        % Params for generating 1 cycle of the stimulus
        stimParams = struct(...
            'displayType', 'CRT-Sony-HorwitzLab', ...
            'displayLuminanceHeadroomPercentage', 0.5, ...
            'backgroundChromaticity', backgroundChromaticity, ...
            'backgroundLuminanceCdM2', backgroundLuminanceCdM2, ...
            'adjustBackgroundChromaticityToEqualizeLandMconeExcitations', adjustBackgroundChromaticityToEqualizeLandMconeExcitations, ...
            'contrast', contrast, ...
            'coneContrasts', coneContrastDirection, ...
            'sizeDegs', 1.1*max(theMRGCmosaic.inputConeMosaic.sizeDegs), ...
            'spatialPhaseIncrementDegs', spatialPhaseIncrementDegs, ...
            'temporalFrequencyHz', temporalFrequencyHz, ...
            'durationSeconds', 1.0/temporalFrequencyHz, ...
            'orientationDegs', orientationsDegs, ...
            'spatialFrequencyCPD', spatialFrequencyCPD, ...
            'opticsIsDiffractionLimited', opticsIsDiffractionLimited);

        % Compute the inputConeMosaic excitation responses
        computeInputConeMosaicResponse(theMRGCmosaic, theOI, thePSFatTheMosaicEccentricity, stimParams, ...
            debugInputConeMosaicResponse, debugStimulusSequence, ...
            theInputConeMosaicResponsesFullFileName);
    end

    if (computeInputConeMosaicResponses) && (computeInputConeMosaicResponsesBasedOnPhotocurrents)
        computeInputConeMosaicPhotocurrentResponse(theInputConeMosaicResponsesFullFileName, photocurrentParams);
    end


    if (computeMRGCMosaicResponses) || (onlyVisualizeMRGCresponses)

        if (~isempty(coneModulationsBasedNonLinearityParamsStruct))
            coneModulationsResponseBasedNonLinearitiesList = coneModulationsBasedNonLinearityParamsStruct.nonLinearitiesList;
        else
            coneModulationsResponseBasedNonLinearitiesList = {};
        end

        if (~isempty(photocurrentsBasedMRGCNonLinearityParamsStruct))
            photocurrentResponseBasedNonLinearitiesList = photocurrentsBasedMRGCNonLinearityParamsStruct.nonLinearitiesList;
        else
            photocurrentResponseBasedNonLinearitiesList = {};
        end

        computeAllMRGCMosaicResponses(...
            theInputConeMosaicResponsesFullFileName, ...
            theMRGCMosaicResponsesFullFileName, ...
            coneModulationsResponseBasedNonLinearitiesList, ...
            photocurrentResponseBasedNonLinearitiesList, ...
            onlyVisualizeMRGCresponses, ...
            figureDir);
    end
end % computeSimulationForCurrentStimulus


%
% Supporting functions
%
%
function computeAllMRGCMosaicResponses(theInputConeMosaicResponsesFullFileName, theMRGCMosaicResponsesFullFileName, ...
    coneModulationsResponseBasedNonLinearitiesList, ...
    photocurrentResponseBasedNonLinearitiesList, ...
    onlyVisualizeMRGCresponses, ...
    figureDir)

    if (~onlyVisualizeMRGCresponses)
        % The sincle period cone excitations response of the input cone mosaic
        load(theInputConeMosaicResponsesFullFileName, ...
            'theMRGCmosaic', ...
            'stimParams', ...
            'theInputConeMosaicExcitationsResponse', ...
            'theInputConeMosaicExcitationsNullResponse');
    
        % Compute the NONLINEAR cone-excitations based mRGC mosaic responses to a single period
        [theMRGCmosaicExcitationBasedResponses, temporalSupportSeconds, theMRGCmosaicExcitationBasedLinearResponses] = ...
            computeMRGCMosaicResponses(theMRGCmosaic, ...
                stimParams.temporalSupportSeconds, ...
                theInputConeMosaicExcitationsResponse, ...
                coneModulationsResponseBasedNonLinearitiesList);
    
        fprintf('Max LINEAR response: %f\n', max(abs(theMRGCmosaicExcitationBasedLinearResponses(:))));
        fprintf('Max NON-LINEAR response: %f\n', max(abs(theMRGCmosaicExcitationBasedResponses(:))));


        theMRGCmosaicExcitationBasedResponsesSinglePeriod = struct(...
            'linearResponses', theMRGCmosaicExcitationBasedLinearResponses, ...
            'responses', theMRGCmosaicExcitationBasedResponses, ...
            'temporalSupportSeconds', temporalSupportSeconds);
    
        % Save the single-period, excitations-based responses
        save(theMRGCMosaicResponsesFullFileName, ...
            'theMRGCmosaicExcitationBasedResponsesSinglePeriod', ...
            '-v7.3');
    
        % See if we have input cone mosaic photocurrent responses and if we do
        % compute the photocurrents based mRGC mosaic responses
        allData = who('-file', theInputConeMosaicResponsesFullFileName);
        photocurrentResponsesHaveBeenComputed = ismember('theInputConeMosaicPeriodicPhotocurrentsResponse', allData);

        if (photocurrentResponsesHaveBeenComputed)
    
            % We have photocurrent based inputConeMosaic responses,
            % so compute mRGC responses based on those as well
             load(theInputConeMosaicResponsesFullFileName, ...
                'theInputConeMosaicPeriodicExcitationsResponse', ...
                'theInputConeMosaicPeriodicExcitationsTemporalSupportSeconds', ...
                'theInputConeMosaicPeriodicPhotocurrentTemporalSupportSeconds', ...
                'theInputConeMosaicPeriodicPhotocurrentsResponse', ...
                'theInputConeMosaicBackgroundPhotocurrents');
    
            % cone modulations-based mRGC responses (periodic)
            [theMRGCmosaicResponses, temporalSupportSeconds, theMRGCmosaicLinearResponses] = ...
                computeMRGCMosaicResponses(theMRGCmosaic, ...
                    theInputConeMosaicPeriodicExcitationsTemporalSupportSeconds, ...
                    theInputConeMosaicPeriodicExcitationsResponse, ...
                    coneModulationsResponseBasedNonLinearitiesList);
    
            theMRGCmosaicExcitationsBasedResponsesPeriodic = struct(...
                'linearResponses', theMRGCmosaicLinearResponses, ...
                'responses', theMRGCmosaicResponses, ...
                'temporalSupportSeconds', temporalSupportSeconds);
    
            % photocurrent-based mRGC responses (periodic)
            [theMRGCmosaicResponses, temporalSupportSeconds, theMRGCmosaicLinearResponses] = ...
                computeMRGCMosaicResponses(theMRGCmosaic, ...
                    theInputConeMosaicPeriodicPhotocurrentTemporalSupportSeconds, ...
                    theInputConeMosaicPeriodicPhotocurrentsResponse, ...
                    photocurrentResponseBasedNonLinearitiesList);
    
            theMRGCmosaicPhotocurrentsBasedResponsesPeriodic = struct(...
                'linearResponses', theMRGCmosaicLinearResponses, ...
                'responses', theMRGCmosaicResponses, ...
                'temporalSupportSeconds', temporalSupportSeconds);
    
            % Extract single period responses
            dToriginal = theMRGCmosaicExcitationBasedResponsesSinglePeriod.temporalSupportSeconds(2)-theMRGCmosaicExcitationBasedResponsesSinglePeriod.temporalSupportSeconds(1);
            dT = temporalSupportSeconds(2)-temporalSupportSeconds(1);
            tOneStimulusCycle = theMRGCmosaicExcitationBasedResponsesSinglePeriod.temporalSupportSeconds(end)-theMRGCmosaicExcitationBasedResponsesSinglePeriod.temporalSupportSeconds(1);
            idx = find(temporalSupportSeconds >= temporalSupportSeconds(end)-(tOneStimulusCycle+0.5*dToriginal-dT));
    
            temporalSupportSeconds = temporalSupportSeconds(idx);
            theMRGCmosaicResponses = theMRGCmosaicResponses(:, idx, :);
            theMRGCmosaicLinearResponses = theMRGCmosaicLinearResponses(:, idx, :);
    
            theMRGCmosaicPhotocurrentsBasedResponsesSinglePeriod = struct(...
                'linearResponses', theMRGCmosaicLinearResponses, ...
                'responses', theMRGCmosaicResponses, ...
                'temporalSupportSeconds', temporalSupportSeconds);
    
            % Append the periodic, excitations, and photocurrents-based responses
            save(theMRGCMosaicResponsesFullFileName, ...
                'theMRGCmosaicExcitationsBasedResponsesPeriodic', ...
                'theMRGCmosaicPhotocurrentsBasedResponsesPeriodic', ...
                'theMRGCmosaicPhotocurrentsBasedResponsesSinglePeriod', ...
                '-append');
        end
    else

        % See if we have input cone mosaic photocurrent responses and if we do
        % compute the photocurrents based mRGC mosaic responses
        allData = who('-file', theInputConeMosaicResponsesFullFileName);
        photocurrentResponsesHaveBeenComputed = ismember('theInputConeMosaicPeriodicPhotocurrentsResponse', allData);

        if (photocurrentResponsesHaveBeenComputed )
            load(theMRGCMosaicResponsesFullFileName, ...
                'theMRGCmosaicExcitationBasedResponsesSinglePeriod', ...
                'theMRGCmosaicExcitationsBasedResponsesPeriodic', ...
                'theMRGCmosaicPhotocurrentsBasedResponsesPeriodic', ...
                'theMRGCmosaicPhotocurrentsBasedResponsesSinglePeriod');
        else
            load(theMRGCMosaicResponsesFullFileName, ...
                'theMRGCmosaicExcitationBasedResponsesSinglePeriod', ...
                'theMRGCmosaicExcitationsBasedResponsesPeriodic');
        end

    end


    % Visualize responses
    mRGCsNum = size(theMRGCmosaicExcitationBasedResponsesSinglePeriod.responses,3);
    maxExcitationsBasedResponse = max( ...
        [prctile(abs(theMRGCmosaicExcitationBasedResponsesSinglePeriod.responses(:)),95)
         prctile(abs(theMRGCmosaicExcitationBasedResponsesSinglePeriod.linearResponses(:)),95) ]);

    if (photocurrentResponsesHaveBeenComputed)
        idx = find(theMRGCmosaicPhotocurrentsBasedResponsesPeriodic.temporalSupportSeconds>0.5);
        maxPhotocurrentsBasedResponse = max(...
            [prctile(max(abs(squeeze(theMRGCmosaicPhotocurrentsBasedResponsesPeriodic.responses(1,idx,:)))),95) ...
             prctile(abs(theMRGCmosaicPhotocurrentsBasedResponsesSinglePeriod.linearResponses(:)), 95)]);
    end

    hFig = figure(1); clf;
    set(hFig, 'Position', [10 10 1984 768], 'Color', [1 1 1]);

    videoOBJ = VideoWriter(fullfile(figureDir,'mRGCnonLinearity'), 'MPEG-4');
    videoOBJ.FrameRate = 10;
    videoOBJ.Quality = 100;
    videoOBJ.open();


    excitationsBasedTicks = -1:0.1:1;
    photocurrentsBasedTicks = -10:2:10;

    for exemplarRGCindex = 1:mRGCsNum

        set(hFig, 'Name', sprintf('mRGC #%d of %d', exemplarRGCindex, mRGCsNum));

        % ----- The non-linear activation functions ----
        % Cone-excitations based response activation function
        ax = subplot('Position', [0.02 0.57 0.18 0.37]);
        theLinearResponse = theMRGCmosaicExcitationBasedResponsesSinglePeriod.linearResponses(1,:,exemplarRGCindex);
        theNonLinearResponse = theMRGCmosaicExcitationBasedResponsesSinglePeriod.responses(1,:,exemplarRGCindex);
        plotNonLinearity(ax, theLinearResponse, theNonLinearResponse, maxExcitationsBasedResponse, ...
            coneModulationsResponseBasedNonLinearitiesList, ...
            excitationsBasedTicks, false, sprintf('cone excitations - based\nactivation function'));

        if (photocurrentResponsesHaveBeenComputed)
            % Photocurrents based response activation function (single period)
            ax = subplot('Position', [0.02 0.09 0.18 0.37]);
            theLinearResponse = theMRGCmosaicPhotocurrentsBasedResponsesSinglePeriod.linearResponses(1,:,exemplarRGCindex);
            theNonLinearResponse = theMRGCmosaicPhotocurrentsBasedResponsesSinglePeriod.responses(1,:,exemplarRGCindex);
            plotNonLinearity(ax, theLinearResponse, theNonLinearResponse, maxPhotocurrentsBasedResponse, ...
                photocurrentResponseBasedNonLinearitiesList, ...
                photocurrentsBasedTicks, true, sprintf('photocurrents - based\nactivation function'));
        end


        % The full response
        if (photocurrentResponsesHaveBeenComputed)
            % The periodic cone excitations based mRGC response
            ax = subplot('Position', [0.25 0.57 0.55 0.37]);
            theResponse = theMRGCmosaicExcitationsBasedResponsesPeriodic.responses(1,:,exemplarRGCindex);
            theLinearResponse = theMRGCmosaicExcitationsBasedResponsesPeriodic.linearResponses(1,:,exemplarRGCindex);
            theTemporalSupport = theMRGCmosaicExcitationsBasedResponsesPeriodic.temporalSupportSeconds;
            plotResponse(ax, theTemporalSupport, theResponse, theLinearResponse, maxExcitationsBasedResponse, ...
                excitationsBasedTicks, false, true, 'cone excitations - based mRGC responses (full simulation time)');

            % The periodic photocurrents based mRGC response
            ax = subplot('Position', [0.25 0.09 0.55 0.37]);
            theResponse = theMRGCmosaicPhotocurrentsBasedResponsesPeriodic.responses(1,:,exemplarRGCindex);
            theLinearResponse = theMRGCmosaicPhotocurrentsBasedResponsesPeriodic.linearResponses(1,:,exemplarRGCindex);
            theTemporalSupport = theMRGCmosaicPhotocurrentsBasedResponsesPeriodic.temporalSupportSeconds;
            plotResponse(ax, theTemporalSupport, theResponse, theLinearResponse, maxPhotocurrentsBasedResponse, ...
                photocurrentsBasedTicks, true, true, 'photocurrents - based mRGC responses (full simulation time)');
        end



        % One period of the cone excitations based mRGC response
        ax = subplot('Position', [0.86 0.57 0.13 0.35]);
        theLinearResponse = theMRGCmosaicExcitationBasedResponsesSinglePeriod.linearResponses(1,:,exemplarRGCindex);
        theResponse = theMRGCmosaicExcitationBasedResponsesSinglePeriod.responses(1,:,exemplarRGCindex);
        theTemporalSupport = theMRGCmosaicExcitationBasedResponsesSinglePeriod.temporalSupportSeconds;
        plotResponse(ax, theTemporalSupport, theResponse, theLinearResponse, maxExcitationsBasedResponse, ...
            excitationsBasedTicks, false, false, sprintf('1 period'));

        if (photocurrentResponsesHaveBeenComputed)
            % One period of the photocurrents based mRGC response
            ax = subplot('Position', [0.86 0.09 0.13 0.35]);
            theResponse = theMRGCmosaicPhotocurrentsBasedResponsesSinglePeriod.responses(1,:,exemplarRGCindex);
            theLinearResponse = theMRGCmosaicPhotocurrentsBasedResponsesSinglePeriod.linearResponses(1,:,exemplarRGCindex);
            theTemporalSupport = theMRGCmosaicPhotocurrentsBasedResponsesSinglePeriod.temporalSupportSeconds;
            plotResponse(ax, theTemporalSupport, theResponse, theLinearResponse, maxPhotocurrentsBasedResponse, ...
                photocurrentsBasedTicks, true, false, sprintf('1 period'));
        end

        drawnow;
        videoOBJ.writeVideo(getframe(hFig));
    end

    videoOBJ.close();

end


function plotResponse(ax, theTemporalSupport, theResponse, theLinearResponse, maxResponse, yTicks, showXlabel, showLegend, plotTitle)
    linearColor = [1 0 0];
    nonLinearColor = [0.5 0.5 1.0];
    plot(ax, theTemporalSupport*1e3, theLinearResponse, 'k-', 'LineWidth', 2.0, 'Color', 0.75*linearColor);
    hold(ax, 'on')
    p1 = scatter(ax, theTemporalSupport*1e3, theLinearResponse, 100, ...
        'MarkerFaceColor', linearColor, 'MarkerFaceAlpha', 0.9, 'MarkerEdgeColor', 0.75*linearColor);
    plot(ax, theTemporalSupport*1e3, theResponse, '-', 'LineWidth', 2.0, 'Color', nonLinearColor);
    p2 = scatter(ax, theTemporalSupport*1e3, theResponse, 100,  ...
        'MarkerFaceColor', nonLinearColor, 'MarkerFaceAlpha', 0.9, 'MarkerEdgeColor', 0.75*nonLinearColor);
    hold(ax, 'on')
    plot(ax, theTemporalSupport*1e3, theResponse*0, 'k-', 'LineWidth', 1.0);
    if (showLegend)
        legend(ax, [p1 p2], {'input mRGC response (Rin)', 'output mRGC respone (Rout)'}, 'Location', 'NorthEast', 'NumColumns', 1);
    end
    hold(ax, 'off')
    xTickMilliseconds = 0:1000:30000;
    set(ax, 'YLim', maxResponse * [-1.05 1.05], 'XLim', [theTemporalSupport(1) theTemporalSupport(end)]*1e3, 'FontSize', 16);
    set(ax, 'YTick', yTicks, 'XTick', 0:1000:10000, 'XTickLabel', sprintf('%2.0f\n', xTickMilliseconds));
    xtickangle(ax, 90);
    grid(ax, 'on')
    title(plotTitle);
    if (showXlabel)
        xlabel(ax, 'time (msec)')
    end
    ylabel(ax, 'mRGC response');
end


function plotNonLinearity(ax, theLinearResponse, theResponse, maxResponse, nonLinearitiesList, xyTicks, showXlabel, plotTitle)
    plot(ax, maxResponse*[-1 1], [0 0], 'k-', 'LineWidth', 1.0);
    hold(ax, 'on')
    plot(ax, [0 0], maxResponse*[-1 1], 'k-', 'LineWidth', 1.0);
    

    if (isstruct(nonLinearitiesList))
        theNonLinearityStruct = nonLinearitiesList;
        if (...
                    strcmp(theNonLinearityStruct.sourceSignal, 'compositeResponse') && ...
                    strcmp(theNonLinearityStruct.type, 'Naka Rushton') ...
                )
            p1 = plot(ax, theNonLinearityStruct.params.RinHalfWaveRectifierThreshold*[1 1], maxResponse*[-1 1], 'r--', 'LineWidth', 1.0);
            p2 = plot(ax, theNonLinearityStruct.params.Rin50*[1 1], maxResponse*[-1 1], 'b--', 'LineWidth', 1.0);
        end
    else
        for i = 1:numel(nonLinearitiesList)
            theNonLinearityStruct = nonLinearitiesList{i};
            if (...
                    strcmp(theNonLinearityStruct.sourceSignal, 'compositeResponse') && ...
                    strcmp(theNonLinearityStruct.type, 'Naka Rushton') ...
                )
                p1 = plot(ax, theNonLinearityStruct.params.RinHalfWaveRectifierThreshold*[1 1], maxResponse*[-1 1], 'r--', 'LineWidth', 1.0);
                p2 = plot(ax, theNonLinearityStruct.params.Rin50*[1 1], maxResponse*[-1 1], 'b--', 'LineWidth', 1.0);
            end
        end
    end

    p3 = scatter(ax, theLinearResponse, theResponse, 100, ...
        'LineWidth', 1.0, 'MarkerFaceAlpha', 0.5, 'MarkerEdgeAlpha', 0.5, ...
        'MarkerFaceColor', [0.7 0.5 0.0], 'MarkerEdgeColor', 'none');
    plot(ax, maxResponse*[-1 1], maxResponse*[-1 1], 'k--');
    hold(ax, 'off')

    legend(ax, [p1 p2 p3], {'RinHWrectThreshold', 'Rin50', 'Rout'}, 'Location', 'SouthEast');
    set(ax, 'YLim', maxResponse * [-1 1], 'XLim', maxResponse * [-1 1], 'FontSize', 16);
    set(ax, 'XTick', xyTicks, 'YTick', xyTicks);
    xtickangle(ax, 90);
    grid(ax, 'on')
    axis(ax, 'square');
    title(plotTitle);
    if (showXlabel)
        xlabel(ax, 'input mRGC response (Rin)');
    end
    ylabel(ax, 'output mRGC response (Rout)');
end


function [theMRGCmosaicResponses, theMRGCmosaicResponseTemporalSupportSeconds, theLinearMRGCmosaicResponses] = ...
    computeMRGCMosaicResponses(...
        theMRGCmosaic, ...
        theInputConeMosaicTemporalSupportSeconds, ...
        theInputConeMosaicResponse, ...
        nonLinearitiesList)

    nTimeBins = size(theInputConeMosaicResponse,1);
    nCones = size(theInputConeMosaicResponse,2);

    % Compute the mRGCmosaic response
    [theMRGCmosaicResponses, ~, theMRGCmosaicResponseTemporalSupportSeconds, theLinearMRGCmosaicResponses] = theMRGCmosaic.compute(...
            reshape(theInputConeMosaicResponse, [1 nTimeBins nCones]), ...
            theInputConeMosaicTemporalSupportSeconds, ...
            'nonLinearitiesList', nonLinearitiesList);

end


function computeInputConeMosaicPhotocurrentResponse(theInputConeMosaicResponsesFullFileName, photocurrentParams)

    load(theInputConeMosaicResponsesFullFileName, ...
        'theMRGCmosaic', ...
        'stimParams', ...
        'theInputConeMosaicExcitationsTemporalSupportSeconds', ...
        'theInputConeMosaicExcitationsResponse', ...
        'theInputConeMosaicExcitationsNullResponse');

    % Transform cone modulations to cone excitations
    if (stimParams.coneMosaicModulationBasedResponse)
        theInputConeMosaicExcitationsNullResponse = reshape(theInputConeMosaicExcitationsNullResponse, [1 numel(theInputConeMosaicExcitationsNullResponse)]);

        % Transform from modulations to excitations
        %Rmod = (Recx-Ro)/Ro -> (Rmod+1)*Ro = RExc
        theInputConeMosaicExcitationsResponse = theInputConeMosaicExcitationsResponse + 1;
        theInputConeMosaicExcitationsResponse = bsxfun(@times, theInputConeMosaicExcitationsResponse, theInputConeMosaicExcitationsNullResponse);
    end

    % Compute # of warm up periods
    stimulusPeriodDuration = 1/stimParams.temporalFrequencyHz;

    nWarmUpPeriods = max([1 ceil(photocurrentParams.osBiophysicalModelWarmUpTimeSeconds/stimulusPeriodDuration)]);

    debugInputConeMosaicPcurrentResponse = false;
    plotTitle = 'debug';

    % Compute photocurrents
    [theInputConeMosaicPeriodicPhotocurrentTemporalSupportSeconds, ...
     theInputConeMosaicPeriodicPhotocurrentsResponse, ...
     theInputConeMosaicBackgroundPhotocurrents, ...
     theInputConeMosaicPeriodicExcitationsResponse, ...
     theInputConeMosaicPeriodicExcitationsTemporalSupportSeconds] = RGCMosaicAnalyzer.compute.photocurrentsForOneStimulusPeriod(...
        theMRGCmosaic.eccentricityDegs, ...
        stimParams.temporalSupportSeconds(1:end-1), ...   % Get rid of last point which is a repeat of the first point
        theInputConeMosaicExcitationsResponse(1:end-1,:), ...       % Get rid of last point which is a repeat of the first point
        nWarmUpPeriods, ...
        photocurrentParams.temporalResolutionSeconds, ...
        photocurrentParams.osBiophysicalModelTemporalResolutionSeconds, ...
        theMRGCmosaic.inputConeMosaic.coneTypes, ...
        [], ...
        debugInputConeMosaicPcurrentResponse, ...
        plotTitle, ...
        'onlyKeepResponseDuringLastTwoStimulusPeriods', false, ...
        'onlyKeepResponseDuringLastStimulusPeriod', false);

     % Transform cone excitations back to cone modulations
    if (stimParams.coneMosaicModulationBasedResponse)
        % Transform from modulations to excitations
        %Rmod = (Recx-Ro)/Ro -> (Rmod+1)*Ro = RExc

        idx = find(theInputConeMosaicExcitationsNullResponse == 0);
        normalizingResponse = 1./ theInputConeMosaicExcitationsNullResponse;
        normalizingResponse(idx) = 0;
        theInputConeMosaicPeriodicExcitationsResponse = bsxfun(@times, theInputConeMosaicPeriodicExcitationsResponse, normalizingResponse) - 1;
    end


    save(theInputConeMosaicResponsesFullFileName, ...
        'theInputConeMosaicPeriodicPhotocurrentTemporalSupportSeconds', ...
        'theInputConeMosaicPeriodicPhotocurrentsResponse', ...
        'theInputConeMosaicBackgroundPhotocurrents', ...
        'theInputConeMosaicPeriodicExcitationsResponse', ...
        'theInputConeMosaicPeriodicExcitationsTemporalSupportSeconds', ...
        '-append');
end


function computeInputConeMosaicResponse(theMRGCmosaic, theOI, thePSFatTheMosaicEccentricity, stimParams, ...
    debugInputConeMosaicResponse, debugStimulusSequence, ...
    theInputConeMosaicResponsesFullFileName)

    % Determine the stimulus pixel resolution to be a fraction of the minimum cone aperture 
    % or cone spacing in the mosaic here, half of the cone spacing
    theMetric = 'cone aperture';  % choose from {'cone aperture' or cone spacing'}
    if (stimParams.opticsIsDiffractionLimited)
        theFraction = 0.1;
    else
        theFraction = 0.25;
    end
    targetRGCindices =  1:theMRGCmosaic.rgcsNum;
    stimulusResolutionDegs = ...
        RGCMosaicConstructor.helper.simulateExperiment.stimulusResolutionFromConeApertureOrConeSpacing(...
            theMRGCmosaic, targetRGCindices, theFraction, theMetric);
    stimParams.resolutionDegs = stimulusResolutionDegs;

    % Generate presentation display, 20% luminance headroom
    viewingDistanceMeters = 4;
    
    % Generate presentation display
    thePresentationDisplay = visualStimulusGenerator.presentationDisplay(...
        theMRGCmosaic.inputConeMosaic.wave, ...
        stimulusResolutionDegs, ...
        viewingDistanceMeters, ...
        'displayType', stimParams.displayType, ...
        'meanLuminanceCdPerM2', stimParams.backgroundLuminanceCdM2, ...
        'luminanceHeadroom', stimParams.displayLuminanceHeadroomPercentage, ...
        'bitDepth', 20);

    if (stimParams.adjustBackgroundChromaticityToEqualizeLandMconeExcitations)
        [stimParams.backgroundChromaticity, ...
         stimParams.backgroundLuminanceCdM2, ...
         LMSbefore, LMSafter] = RGCMosaicConstructor.helper.simulateExperiment.updateBackgroundToAchieveEqualLandMconeActivation(...
              thePresentationDisplay, ...
              stimParams.backgroundChromaticity, ...
              stimParams.backgroundLuminanceCdM2); 
    end


    % Generate the spatial modulation patterns for all spatial phases of the drifting grating
    [theDriftingGratingSpatialModulationPatterns, ...
     spatialSupportDegs, spatialPhasesDegs, ...
     temporalSupportSeconds, temporalRamp] = visualStimulusGenerator.driftingGratingModulationPatterns(stimParams);


    % Generate scenes for the different frames of the drifting grating and for the null stimulus
    [theDriftingGratingFrameScenes, theNullStimulusScene] = visualStimulusGenerator.stimulusFramesScenes(...
        thePresentationDisplay, stimParams, theDriftingGratingSpatialModulationPatterns, ...
        'frameIndexToCompute', [], ... % [] field indicates that all stimulus frame scenes must be computed
        'validateScenes', ~true);

    % Compute input cone mosaic response to this orientation & spatial frequency
    stimulusPosition = 'mosaic-centered';

    % Set the mosaic integration time equal to the duration of one stimulus frame
    theMRGCmosaic.inputConeMosaic.integrationTime = temporalSupportSeconds(2)-temporalSupportSeconds(1);

    % Cone-modulation based responses
    stimParams.coneMosaicModulationBasedResponse = true;

    % Compute cone mosaic responses to each stimulus frame
    [theInputConeMosaicExcitationsResponse, theInputConeMosaicExcitationsNullResponse] = ...
        RGCMosaicConstructor.helper.simulateExperiment.inputConeMosaicResponseToStimulusFrameSequence(...
            theMRGCmosaic, ...
            theOI, ...
            theNullStimulusScene, ...
            theDriftingGratingFrameScenes, ...
            stimulusPosition, ...
            stimParams.coneMosaicModulationBasedResponse, ...
            'visualizeResponse', debugInputConeMosaicResponse, ...
            'visualizeStimulusSequence', debugStimulusSequence, ...
            'thePresentationDisplayForVisualizingOpticalSceneOrImage', thePresentationDisplay);

    % Temporal support for cone mosaic excitations
    theInputConeMosaicExcitationsTemporalSupportSeconds = temporalSupportSeconds;

    % Update stimParams
    stimParams.spatialPhasesDegs = spatialPhasesDegs;
    stimParams.temporalSupportSeconds = temporalSupportSeconds;
    stimParams.temporalRamp = temporalRamp;

    % Save results
    fprintf('Saving computed input cone mosaic STF cone excitation responses to %s.\n', theInputConeMosaicResponsesFullFileName);
    save(theInputConeMosaicResponsesFullFileName, ...
        'theMRGCmosaic', ...
        'thePSFatTheMosaicEccentricity', ...
        'stimParams', ...
        'theInputConeMosaicExcitationsTemporalSupportSeconds', ...
        'theInputConeMosaicExcitationsResponse', ...
        'theInputConeMosaicExcitationsNullResponse', ...
        '-v7.3');

end

