function t_mRGCMosaicVisualize(options)
% Visualize prebaked mRGCMosaics and the cone pooling maps of individual cells
%
% Description:
%    Demonstrates the following:
%    (i)   how to load a pre-baked midget RGC mosaic, 
%    (ii)  visualize the mosaic of RF centers,
%    (iii) visualize the PSF of the optics used to build the mosaic
%    (iv)  visualize the RF center and surround cone pooling maps of
%          individual cells within the mosaic
%
%  This is set up with key/value pairs that demonstate how to select different
%  options. Different choices are illustrated in the examples
%  in the source code.
%
% Optional key/value pairs
%    See source code arguments block for a list of key/value pairs.

% History:
%    07/28/25  NPC  Wrote it.

% Examples:
%{

%
% NOTE: To run any RGC-related ISETBio code, such as this tutorial, users must follow
% the directions discribed in:
%    https://github.com/isetbio/isetbio/wiki/Retinal-ganglion-cell-(RGC)-mosaics
% under section "Configuring ISETBio to access RGC resources and run RGC simulations"
%

    t_mRGCMosaicVisualize(...
        'rgcMosaicName', 'JCNpaperTemporal7DegsMosaic', ...
        'opticsSubjectName', 'JCNpaperDefaultSubject');

    % Visualize a mosaic synthesized at 10 deg along the temporal meridian
    t_mRGCMosaicVisualize(...
        'rgcMosaicName', 'JCNpaperTemporal10DegsMosaic', ...
        'opticsSubjectName', 'JCNpaperDefaultSubject');

%}


arguments

    % ---- Mosaic specifiers for selecting a prebaked mRGC mosaic ---

    % See RGCMosaicConstructor.helper.utils.initializeRGCMosaicGenerationParameters
    % for what is available and to add new mosaics
    options.rgcMosaicName (1,:) char = 'JCNpaperNasal2DegsTinyMosaic';


    % ---- Which species to employ ----
    % Choose between {'macaque', 'human'}. If 'macaque' is chosen, the input
    % cone mosaic has a 1:1 L/M cone ratio.
    options.coneMosaicSpecies  (1,:) char {mustBeMember(options.coneMosaicSpecies,{'human','macaque'})} = 'human';

     % ----- Which subject optics to employ -----
    options.opticsSubjectName (1,:) ...
        char ...
        {...
        mustBeMember(options.opticsSubjectName, ...
            { ...
            'JCNpaperDefaultSubject' ...
            'JCNpaperSecondSubject' ...
            'VSS2024TalkFirstSubject' ...
            'VSS2024TalkSecondSubject' ...
            'JCNpaperStrehlRatio_0.87' ...
            'JCNpaperStrehlRatio_0.72' ...
            'JCNpaperStrehlRatio_0.59' ...
            'JCNpaperStrehlRatio_0.60' ...
            'JCNpaperStrehlRatio_0.27' ...
            'JCNpaperStrehlRatio_0.23' ...
            'JCNpaperStrehlRatio_0.21' ...
            'JCNpaperStrehlRatio_0.19' ...
            'JCNpaperStrehlRatio_0.09' ...
            } ...
            ) ...
        } ...
        = 'JCNpaperDefaultSubject';


    % ------ targetVisualSTF options ----
    % Options are : {'default', 'x1.3 RsRcRatio'}
    % These are with respect to the macaque data of the Croner & Kaplan '95 study
    % 'default': target the mean Rs/Rc, and the mean Ks/Kc (Rs/Rc)^2
    % See RGCMosaicConstructor.helper.surroundPoolingOptimizerEngine.generateTargetVisualSTFmodifiersStruct
    % for all existing options
    options.targetVisualSTFdescriptor (1,:) char = 'default';


    % ------ Visualization options ----
    % Visualize cone pooling maps for a target RGC
    options.targetRGCindexForVisualizingConePoolingMaps (1,:) double = [];

    % Whether to generate a video of RFpooling maps along the horizontal meridian
    options.generateVideoOfRFpoolingMapsAlongHorizontalMeridian (1,1) logical = false;

    % Whether to close previously open figures
    options.closePreviouslyOpenFigures (1,1) logical = true;
end


% Set flags from key/value pairs

% Mosaic specifiers for selecting a prebaked mRGC mosaic
rgcMosaicName = options.rgcMosaicName;
coneMosaicSpecies = options.coneMosaicSpecies;
opticsSubjectName = options.opticsSubjectName;
targetVisualSTFdescriptor = options.targetVisualSTFdescriptor;

% Visualization options
targetRGCindexForVisualizingConePoolingMaps = options.targetRGCindexForVisualizingConePoolingMaps;
generateVideoOfRFpoolingMapsAlongHorizontalMeridian = options.generateVideoOfRFpoolingMapsAlongHorizontalMeridian;

% Close previously open figures
closePreviouslyOpenFigures = options.closePreviouslyOpenFigures;
if (closePreviouslyOpenFigures)
    % Close any stray figs
    close all;
end


% Load the mRGCmosaic specified by the passed parameters:
%   coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor
% and generate the optics that were used to synthesize the mosaic
[theMRGCmosaic, ~, thePSFatTheMosaicEccentricity] = mRGCMosaic.loadPrebakedMosaic(...
        coneMosaicSpecies, opticsSubjectName, rgcMosaicName, targetVisualSTFdescriptor, ...
        'computeTheMosaicOptics', true);


% Subdirectory for exporting the generated PDFs
exportVisualizationPDFdirectory = 'mosaicVisualizationPDFs';


% mRGC mosaic visualization limits and ticks (excluding the extent of the
% input cone mosaic)
visualizedWidthDegs = theMRGCmosaic.sizeDegs(1)*0.7;
visualizedHeightDegs = theMRGCmosaic.sizeDegs(2);
domainVisualizationLimits(1:2) = theMRGCmosaic.eccentricityDegs(1) + 0.5 * visualizedWidthDegs * [-1 1];
domainVisualizationLimits(3:4) = theMRGCmosaic.eccentricityDegs(2) + 0.14 * visualizedHeightDegs * [-1 1];
domainVisualizationTicks = struct(...
    'x', theMRGCmosaic.eccentricityDegs(1) + 0.5 * visualizedWidthDegs * [-1 -0.5 0 0.5 1], ...
    'y', theMRGCmosaic.eccentricityDegs(2) + 0.5 * visualizedHeightDegs * [-1 -0.5 0 0.5 1]);


% Visualize RF centers using the spatial extent of cones whose RF center pooling weights
% are >= mRGCMosaic.sensitivityAtPointOfOverlap;
% This representation is like the representation used in visualizing 
% mosaics of RGCs in typical in-vitro experiments (e.g. by the Chichilnisky lab)
minCenterConeWeight = mRGCMosaic.sensitivityAtPointOfOverlap;

% Get ready for publication-quality visualization
ff = PublicationReadyPlotLib.figureComponents('1x1 giant rectangular-double wide mosaic', ...
    'darkScheme', true);

% Plot the mosaic of mRGC RF centers only
hFig = figure(1); clf;
theAxes = PublicationReadyPlotLib.generatePanelAxes(hFig,ff);
ax = theAxes{1,1};

tmp = ff.backgroundColor;
ff.backgroundColor = ff.legendBackgroundColor;
ff.legendBackgroundColor = tmp;

theMRGCmosaic.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'identifyInputCones', false, ...
    'identifyPooledCones', false, ...
    'minConeWeightVisualized', minCenterConeWeight, ...
    'centerSubregionContourSamples', 32, ...
    'plottedRFoutlineFaceAlpha', 1.0, ...
    'plottedRFoutlineLineWidth', 1.0, ...
    'plottedRFoutlineFaceColor', [1 1 1], ...
    'plottedRFoutlineEdgeColor',  [0 0 0], ...
    'domainVisualizationLimits', domainVisualizationLimits, ...
    'domainVisualizationTicks', domainVisualizationTicks, ...
    'plotTitle', sprintf('min center weight visualized: %2.3f', minCenterConeWeight), ...
    'withFigureFormat', ff, ...
    'backgroundColor', ff.legendBackgroundColor, ...
    'clearAxesBeforeDrawing', false, ...
    'visualizationPDFfileName', sprintf('fullMRGCmosaicMinCenterConeWeight_%2.3f', minCenterConeWeight), ...
    'exportVisualizationPDF', true, ...
    'exportVisualizationPNG', true, ...
    'exportVisualizationPDFdirectory', exportVisualizationPDFdirectory);
hold(ax, 'on');

% double rendering
theMRGCmosaic.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'identifyInputCones', false, ...
    'identifyPooledCones', false, ...
    'minConeWeightVisualized', minCenterConeWeight, ...
    'centerSubregionContourSamples', 32, ...
    'plottedRFoutlineFaceAlpha', 0.5, ...
    'plottedRFoutlineLineWidth', 4.0, ...
    'plottedRFoutlineEdgeColor', [0 0 0], ...
    'plottedRFoutlineFaceColor',  [0. 1.0 0.0], ...
    'domainVisualizationLimits', domainVisualizationLimits, ...
    'domainVisualizationTicks', domainVisualizationTicks, ...
    'plotTitle', sprintf('min center weight visualized: %2.3f', minCenterConeWeight), ...
    'withFigureFormat', ff, ...
    'backgroundColor', ff.legendBackgroundColor, ...
    'clearAxesBeforeDrawing', false, ...
    'visualizationPDFfileName', sprintf('fullMRGCmosaicMinCenterConeWeight_%2.3f', minCenterConeWeight), ...
    'exportVisualizationPDF', true, ...
    'exportVisualizationPNG', true, ...
    'exportVisualizationPDFdirectory', exportVisualizationPDFdirectory);

theMRGCmosaic.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'identifyInputCones', false, ...
    'identifyPooledCones', false, ...
    'minConeWeightVisualized', minCenterConeWeight, ...
    'centerSubregionContourSamples', 32, ...
    'plottedRFoutlineFaceAlpha', 0.0, ...
    'plottedRFoutlineLineWidth', 2, ...
    'plottedRFoutlineEdgeColor', [0 1 0 ], ...
    'plottedRFoutlineFaceColor',  [0. 1 0.0], ...
    'domainVisualizationLimits', domainVisualizationLimits, ...
    'domainVisualizationTicks', domainVisualizationTicks, ...
    'plotTitle', sprintf('min center weight visualized: %2.3f', minCenterConeWeight), ...
    'withFigureFormat', ff, ...
    'backgroundColor', ff.legendBackgroundColor, ...
    'clearAxesBeforeDrawing', false, ...
    'visualizationPDFfileName', sprintf('fullMRGCmosaicMinCenterConeWeight_%2.3f', minCenterConeWeight), ...
    'exportVisualizationPDF', true, ...
    'exportVisualizationPNG', true, ...
    'exportVisualizationPDFdirectory', exportVisualizationPDFdirectory);


% Visualize RF centers using the spatial extent of cones whose RF center pooling weights
% are > mRGCMosaic.minSensitivityForInclusionOfDivergentConeConnections
% (basically all cones connected to each RF center). This is useful for
% visualizing the degree of RF center overlap
minCenterConeWeight = mRGCMosaic.minSensitivityForInclusionOfDivergentConeConnections;

hFig = figure(2); clf;
theAxes = PublicationReadyPlotLib.generatePanelAxes(hFig,ff);
ax = theAxes{1,1};

theMRGCmosaic.visualize(...
    'figureHandle', hFig, ...
    'axesHandle', ax, ...
    'identifyInputCones', false, ...
    'identifyPooledCones', false, ...
    'plottedRFoutlineFaceColor',  [0 1 0], ...
    'plottedRFoutlineFaceAlpha', 0.5, ...
    'minConeWeightVisualized', minCenterConeWeight, ...
    'plottedRFoutlineFaceAlpha', 1.0, ...
    'plottedRFoutlineLineWidth', 1.0, ...
    'plottedRFoutlineFaceColor',  [0 1 0.4], ...
    'centerSubregionContourSamples', 32, ...
    'domainVisualizationLimits', domainVisualizationLimits, ...
    'domainVisualizationTicks', domainVisualizationTicks, ...
    'plotTitle', sprintf('min center weight visualized: %2.3f', minCenterConeWeight), ...
    'withFigureFormat', ff, ...
    'backgroundColor', ff.legendBackgroundColor, ...
    'clearAxesBeforeDrawing', false, ...
    'visualizationPDFfileName', sprintf('fullMRGCmosaicMinCenterConeWeight_%2.3f', minCenterConeWeight), ...
    'exportVisualizationPDF', true, ...
    'exportVisualizationPNG', true, ...
    'exportVisualizationPDFdirectory', exportVisualizationPDFdirectory);



end



